- .github/workflows/ci.yml
- proto/foxglove/CameraCalibration.proto
- proto/foxglove/Color.proto
- proto/foxglove/CompressedImage.proto
- proto/foxglove/ImageAnnotations.proto
- proto/foxglove/JointState.proto
- proto/foxglove/LocationFix.proto
- proto/foxglove/Log.proto
- proto/foxglove/RawImage.proto
- proto/foxglove/Timestamp.proto
`foxglove.*` Protobuf schemas are updated to match documentation on the website.
Relates to https://github.com/foxglove/studio/issues/3070
> Update Foxglove protobuf definitions, use fixed integer types, use sec/nsec for Timestamp

- ros_foxglove_msgs/CMakeLists.txt
None
Should fix a CMake warning from the build farm: https://build.ros.org/job/Ndev_db__foxglove_msgs__debian_buster_amd64/17/cmake/
https://wiki.ros.org/noetic/Migration#Increase_required_CMake_version_to_avoid_author_warning
> Bump cmake_minimum_required for ROS 1

- ros_foxglove_msgs/.gitattributes
Reduces PR noise by hiding diffs for generated .msg files
> Mark msg files in ros_foxglove_msgs as generated

- ros_foxglove_msgs/ros1/PointsAnnotation.msg
- ros_foxglove_msgs/ros2/PointsAnnotation.msg
- schemas/README.md
- schemas/jsonschema/ImageAnnotations.json
- schemas/jsonschema/PointsAnnotation.json
- schemas/proto/foxglove/PointsAnnotation.proto
- schemas/ros1/PointsAnnotation.msg
- schemas/ros2/PointsAnnotation.msg
- schemas/typescript/PointsAnnotation.ts
- src/schemas.ts
Added missing documentation for PointsAnnotation `outline_color` and `thickness` fields
Foxglove Studio depended on the values of these fields, but they were not documented.
Relates to https://github.com/foxglove/studio/issues/4080
> Add missing documentation for PointsAnnotation `outline_color` and `thickness` fields

- internal/schemas.ts
- ros_foxglove_msgs/ros1/CameraCalibration.msg
- ros_foxglove_msgs/ros1/CompressedImage.msg
- ros_foxglove_msgs/ros1/RawImage.msg
- ros_foxglove_msgs/ros2/CameraCalibration.msg
- ros_foxglove_msgs/ros2/CompressedImage.msg
- ros_foxglove_msgs/ros2/RawImage.msg
- schemas/README.md
- schemas/jsonschema/CameraCalibration.json
- schemas/jsonschema/CompressedImage.json
- schemas/jsonschema/RawImage.json
- schemas/jsonschema/index.ts
- schemas/proto/foxglove/CameraCalibration.proto
- schemas/proto/foxglove/CompressedImage.proto
- schemas/proto/foxglove/RawImage.proto
- schemas/ros1/CameraCalibration.msg
- schemas/ros1/CompressedImage.msg
- schemas/ros1/RawImage.msg
- schemas/ros2/CameraCalibration.msg
- schemas/ros2/CompressedImage.msg
- schemas/ros2/RawImage.msg
- schemas/typescript/CameraCalibration.ts
- schemas/typescript/CompressedImage.ts
- schemas/typescript/RawImage.ts
Added information about Foxglove Studio's supported values for CameraCalibration.distortion_model, RawImage.encoding, and CompressedImage.format.
Closes https://github.com/foxglove/schemas/issues/32
> Add documentation about supported field values for image-related topics

- .github/workflows/ci.yml
- python/.gitignore
- python/Makefile
- python/Pipfile
- python/Pipfile.lock
- python/foxglove-schemas-flatbuffer/README.md
- python/foxglove-schemas-flatbuffer/foxglove_schemas_flatbuffer/__init__.py
- python/foxglove-schemas-flatbuffer/pyproject.toml
- python/foxglove-schemas-flatbuffer/setup.cfg
- python/foxglove-schemas-flatbuffer/tests/test_schemas.py
- [Python] New foxglove-schemas-flatbuffer package exporting Python classes for Flatbuffer types and a get_schema() method for retrieving binary .bfbs schemas
This closely resembles the foxglove-schemas-protobuf package
> [Python] Add foxglove-schemas-flatbuffer package

- .github/workflows/ci.yml
- internal/schemas.ts
- ros_foxglove_msgs/ros1/CircleAnnotation.msg
- ros_foxglove_msgs/ros1/PointsAnnotation.msg
- ros_foxglove_msgs/ros2/CircleAnnotation.msg
- ros_foxglove_msgs/ros2/PointsAnnotation.msg
- schemas/README.md
- schemas/flatbuffer/CircleAnnotation.fbs
- schemas/flatbuffer/PointsAnnotation.fbs
- schemas/jsonschema/CircleAnnotation.json
- schemas/jsonschema/ImageAnnotations.json
- schemas/jsonschema/PointsAnnotation.json
- schemas/jsonschema/index.ts
- schemas/proto/foxglove/CircleAnnotation.proto
- schemas/proto/foxglove/PointsAnnotation.proto
- schemas/ros1/CircleAnnotation.msg
- schemas/ros1/PointsAnnotation.msg
- schemas/ros2/CircleAnnotation.msg
- schemas/ros2/PointsAnnotation.msg
- schemas/typescript/CircleAnnotation.ts
- schemas/typescript/PointsAnnotation.ts
I'm a little meh on this change since we already say `2D image space` and a `Point2d` has `x, y` fields.
@jtbandes I think I need to run some script to re-generate the schemas?
> Add units to PointsAnnotation and CircleAnnotation

- internal/schemas.ts
- ros_foxglove_msgs/ros1/PointCloud.msg
- ros_foxglove_msgs/ros2/PointCloud.msg
- schemas/README.md
- schemas/flatbuffer/PointCloud.fbs
- schemas/jsonschema/PointCloud.json
- schemas/jsonschema/index.ts
- schemas/proto/foxglove/PointCloud.proto
- schemas/ros1/PointCloud.msg
- schemas/ros2/PointCloud.msg
- schemas/typescript/PointCloud.ts
These fields do not need to be float 64s, they can also be float 32. This confused a customer who thought they had to send float64.
@jtbandes do we support the other field types or only float32/64? If we don't support the other field types we should remove them.
> Remove "all float64s" comment from PointCloud schema

- internal/generateRos.test.ts
- internal/generateRos.ts
- scripts/updateGeneratedFiles.ts
Do not normalize `time` & `duration` types in `generateRosMsgDefinition`
Changes `generateRosMsgDefinition` to not normalize `time` & `duration` fields to their ROS2 equivalents (e.g. `builtin_interfaces/Time`). This is now done in `generateRosMsg` as `generateRosMsgDefinition` should output a message definition which is compliant with [@foxglove/message-definition](https://github.com/foxglove/message-definition) where e.g. `builtin_interfaces/Time` does not exist.
See https://github.com/foxglove/rosmsg2-serialization/pull/17#issuecomment-1608102161
> Do not normalize time/duration types in generateRosMsgDefinition

- python/foxglove-schemas-protobuf/setup.cfg
Fix import error by requiring at least python `protobuf>=3.20.0`
See #113 for details.
Fixes #113
> Fix import error by requiring at least python `protobuf>=3.20.0`

- .github/workflows/ci.yml
> ci.yml: PyPI uses OIDC for auth

- .github/workflows/ci.yml
- .vscode/settings.json
- README.md
- internal/__snapshots__/exportTypeScriptSchemas.test.ts.snap
- internal/generateMarkdown.ts
- internal/generateRos.ts
- internal/generateTypeScript.ts
- internal/schemas.ts
- python/foxglove-schemas-flatbuffer/README.md
- python/foxglove-schemas-protobuf/README.md
- ros_foxglove_msgs/package.xml
- ros_foxglove_msgs/ros1/CompressedVideo.msg
- ros_foxglove_msgs/ros2/CompressedVideo.msg
- schemas/README.md
- schemas/flatbuffer/CompressedVideo.fbs
- schemas/jsonschema/CompressedVideo.json
- schemas/jsonschema/index.ts
- schemas/omgidl/foxglove/CompressedVideo.idl
- schemas/proto/foxglove/CompressedVideo.proto
- schemas/ros1/CompressedVideo.msg
- schemas/ros2/CompressedVideo.msg
- schemas/typescript/CompressedVideo.ts
Update to latest links and product names.
Includes a pytest downgrade to work around a CI failure https://github.com/ros2/launch/issues/765 (similar to https://github.com/scientific-python/pytest-doctestplus/issues/240)
> Update links and studio references

- .github/workflows/ci.yml
The ros CI action to use node v20 which can no longer run on this version of ubuntu.
> Remove melodic ci 

- .github/workflows/ci.yml
The ros CI action to use node v20 which can no longer run on this version of ubuntu.
This is a repeat of #147 because that was just merged into another branch. Sorry for the confusion.
> Remove Melodic ci action

- python/foxglove-schemas-flatbuffer/setup.cfg
- python/foxglove-schemas-protobuf/setup.cfg
Protobuf doesn't seem to have had big enough updates since the last release, so I just incremented the patch version.
Flatbuffers had field numbers added and I felt like that warranted a minor version bump.
> Fix python CI

- internal/__snapshots__/exportTypeScriptSchemas.test.ts.snap
- internal/schemas.ts
- ros_foxglove_msgs/ros1/RawImage.msg
- ros_foxglove_msgs/ros2/RawImage.msg
- schemas/README.md
- schemas/flatbuffer/RawImage.fbs
- schemas/jsonschema/RawImage.json
- schemas/jsonschema/index.ts
- schemas/omgidl/foxglove/RawImage.idl
- schemas/proto/foxglove/RawImage.proto
- schemas/ros1/RawImage.msg
- schemas/ros2/RawImage.msg
- schemas/typescript/RawImage.ts
- specify that `16UC1` and `32FC1` are interpreted as little endian
Specify that `16UC1` and `32FC1` are interpreted as little endian
<table><tr><th>Before</th><th>After</th></tr><tr><td>
</td><td>
</td></tr></table>
FG-8171
> Update RawImage schema with endianness

- internal/__snapshots__/exportTypeScriptSchemas.test.ts.snap
- internal/schemas.ts
- ros_foxglove_msgs/ros1/CompressedVideo.msg
- ros_foxglove_msgs/ros2/CompressedVideo.msg
- schemas/README.md
- schemas/flatbuffer/CompressedVideo.fbs
- schemas/jsonschema/CompressedVideo.json
- schemas/jsonschema/index.ts
- schemas/omgidl/foxglove/CompressedVideo.idl
- schemas/proto/foxglove/CompressedVideo.proto
- schemas/ros1/CompressedVideo.msg
- schemas/ros2/CompressedVideo.msg
- schemas/typescript/CompressedVideo.ts
Update CompressedVideo documentation for new formats, and describe format and data in more detail
> Update CompressedVideo format strings

- .github/workflows/ci.yml
Running a publish to TestPyPI immediately followed by a publish to the "real" PyPI triggered [an error](https://github.com/foxglove/schemas/actions/runs/12283736365/job/34277883747) due to a file already existing. The workaround recommended in https://github.com/pypa/gh-action-pypi-publish/issues/283#issuecomment-2499296440 is to set `attestations: false` on the TestPyPI publish.
> Fix PyPI publishing

- .github/workflows/ci.yml
None
None
CI [broke recently](https://github.com/foxglove/schemas/actions/runs/12341162294/job/34439471378?pr=159) because Python 3.7 is not supported for Ubuntu 24.04 x64. See https://github.com/actions/setup-python/issues/962. This fixes the `python` job to use Ubuntu 22.04.
> Fix CI errors due to ubuntu 24.04 image rollout

- package.json
None
None
Running yarn install on a newer version adds this to package.json. Committing it to the repo to avoid future random unstaged changes.
> appease node v22

- rust/foxglove/src/channel.rs
- rust/foxglove/src/channel_builder.rs
- rust/foxglove/src/encode.rs
- rust/foxglove/src/lib.rs
- rust/foxglove/src/log_context.rs
- rust/foxglove/src/mcap_writer/mcap_sink.rs
- rust/foxglove/src/metadata.rs
- rust/foxglove/src/tests.rs
- rust/foxglove/src/testutil/log_sink.rs
- rust/foxglove/src/websocket.rs
- rust/foxglove/src/websocket/protocol/client.rs
- rust/foxglove/src/websocket/protocol/server.rs
- Add the last missing docs, and slap on a `#![warn(missing_docs)]` attribute.
- Remove the mostly-useless `PartialMetadata::new()`.
- Expand the `FoxgloveError` somewhat:
- Rename `Fatal` as `Unspecified` and retain the source error for downcasting.
- Add variants for things that don't benefit from being opaque.
> rust: Add missing docs, expand FoxgloveError

- Cargo.lock
- rust/foxglove/Cargo.toml
- Expanded documentation.
- Expanded `FoxgloveError` variants.
- Reworked unstable examples to use higher-level interfaces.
- Reduced visibility of internal websocket symbols.
- Renamed `TypedMessage` trait to `Encode`.
> rust: Bump SDK version to 0.1.1

- .github/release.yml
- .github/workflows/ci.yml
- .github/workflows/draft-release.yml
- .github/workflows/post-release.yml
- .github/workflows/python.yml
- .npmignore
- .vscode/settings.json
- CONTRIBUTING.md
- Cargo.lock
- package.json
- python/foxglove-sdk/Cargo.toml
- scripts/bumpSdkVersion.ts
- yarn.lock
None
None
New release workflows:
- Draft release workflow to bump version number across all SDK packages (rust + python) and draft release notes
- Post release workflow to merge release tag back into main branch
> Add release workflows

- .github/workflows/draft-release.yml
- .github/workflows/post-release.yml
None
None
Fix git permissions in post-release workflow.
> Fix post-release workflow

- rust/foxglove/src/websocket_server.rs
I accidentally put an async method on the `WebSocketServerBlockingHandle`. Don't do that.
> rust: Remove errant async for broadcast_time

- rust/foxglove/src/lib.rs
- rust/foxglove/src/websocket/protocol/server.rs
We had a couple variants that were not conforming to UpperCamelCase as defined by the [naming guidelines](https://rust-lang.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case).
> rust: Use CamelCase for FoxgloveError variants

- package.json
- scripts/generate.ts
None
None
Extended `yarn generate` script to call `cargo run --bin foxglove-proto-gen`, required to generate the rust code.
The rust generation code cannot be directly ported to typescript because it relies on a rust library (prost) to generate its protobuf implementation.
The only remaining codegen that does not live in `yarn generate` is for python; this will become obsolete once https://github.com/foxglove/foxglove-sdk/pull/201 lands.
> Add rust to generate script

- Cargo.lock
- rust/examples-unstable/client-publish/Cargo.toml
- rust/examples-unstable/param-server/Cargo.toml
- rust/examples-unstable/ws-stream-mcap/Cargo.toml
- rust/examples/mcap/Cargo.toml
- rust/examples/ws-server-blocking/Cargo.toml
- rust/examples/ws-server/Cargo.toml
None
None
No need to semver the rust example crates, we do not intend to publish them. Having a version number adds potential confusion for the release script (since they were out of sync with the core package).
> rust: Remove version numbers from example crates

- python/foxglove-sdk/python/examples/live_visualization.py
- python/foxglove-sdk/src/generated/schemas.rs
- typescript/schemas/src/internal/generatePyclass.test.ts
- typescript/schemas/src/internal/generatePyclass.ts
This PR modifies the generated schema structs to improve the serialization of byte arrays. When a struct `Vec` field is constructed, pyo3 will iterate the vec and copy each element. This change updates the `Vec<u8>` fields to accept a python-native type, from which we copy the bytes at once. This doesn't require changing the protobuf interface in the Rust SDK. There may be further optimizations we can make, but this is pretty low-hanging fruit.
This also adds a point cloud channel to the live viz example, taken from the linked blog post.
Earlier profiling showed that this approach (similar code) gave a speedup of ~2. Writing 1000-pt point clouds in a tight loop to an mcap file increases the publishing throughput 2-3x:
<table>
<tr><th>Before</th>
</tr>
<tr><td>
```sh
duration:  1.333925s …
```
> Optimize serialization of byte buffers in Python SDK

- python/foxglove-sdk/python/docs/index.rst
- python/foxglove-sdk/python/examples/write_log.py
- python/foxglove-sdk/python/foxglove/__init__.py
- python/foxglove-sdk/python/foxglove/_foxglove_py/__init__.pyi
- python/foxglove-sdk/src/lib.rs
This fixes the implementation of `PyMcapWriter` to agree with the declared interface. Notably, it exposes the `close` method and documents the auto-closing behavior if a reference to the writer is not held.
To make this easier to work with, this also adds a context-managed function `new_mcap_file`, which frees the user from needing to maintain a reference to the writer. I included 'mcap' in the name since (a) we've decided to expose that name in the Rust SDK, and (b) it makes clear with the output format will be, since we're asking the user to supply a file name.
This also updates the example to produce a basic MCAP file.
> Update MCAP handling in Python SDK

- rust/foxglove/src/runtime.rs
- rust/foxglove/src/websocket.rs
This reduces default logging noise by changing advertisements & subscriptions to `debug`.
I added a more general "server started" info log, and made the tokio runtime messaging debug. I think we could consider not logging anything about "tokio" from the core SDK, but it also seems OK at debug level.
> Downgrade some logging to debug

- rust/examples/ws-server/src/main.rs
- rust/foxglove/src/encode.rs
This updates the auto-generated JSON schema for custom types to inline definitions, rather than including `$ref`s. Current versions of Foxglove do not support the latter.
This specifies the `draft07` version of JSONSchema, which is currently the default in schemars.
I added an enum to the example to confirm that this works (does not produce a 'problem') in the app.
> rust: inline definitions for derived schemas

- Cargo.lock
- python/foxglove-sdk/Cargo.toml
- python/foxglove-sdk/python/examples/live_visualization.py
- python/foxglove-sdk/python/foxglove/__init__.py
- python/foxglove-sdk/python/foxglove/_foxglove_py/__init__.pyi
- python/foxglove-sdk/src/lib.rs
- python/foxglove-sdk/src/websocket_server.rs
- rust/foxglove/src/websocket.rs
This adds a server listener interface to the Python SDK.
This is implemented as a Protocol in python; pyo3 does not support extending a Python class. To provide reasonable typing on `start_server`, that's now a wrapping function in the public package, to avoid the stub interface referencing the external type.
Since the ws-related code is starting to grow in python, I've moved related classes and functions into `websocket_server.rs` (from lib.rs). The exports are still in the top-level `foxglove` package for now.
To support the message data callback, this also adds support for the `ClientPublish` capability and `supported_encodings`.
I updated the existing live_visualization example to exercise this.
> python: Add a server listener that handles client message callbacks

- rust/foxglove/src/websocket.rs
- rust/foxglove/src/websocket/service.rs
- rust/foxglove/src/websocket/service/request.rs
- rust/foxglove/src/websocket/service/tests.rs
- rust/foxglove/src/websocket/tests.rs
- rust/foxglove/src/websocket_server.rs
Websocket service IDs are an implementation detail to accommodate `ws-protocol`. It's not something that our users need to be aware of. Service names need to be unique, and so that should be the handle by which a service is identified or removed. I realized this as I was trying to implement the python plumbing for `remove_services`.
Now we need two maps for indexing services: one by name, one by ID. They need to be synchronized, so I introduced a new `ServiceMap` struct.
> rust: Don't expose websocket service IDs

- rust/examples/ws-services/src/client.rs
- rust/examples/ws-services/src/server.rs
- rust/foxglove/src/websocket/protocol/server.rs
- rust/foxglove/src/websocket/service.rs
- rust/foxglove/src/websocket/service/handler.rs
- rust/foxglove/src/websocket/service/tests.rs
- rust/foxglove/src/websocket/tests.rs
Borrow some good ideas for wrapping callbacks from @eloff's asset handler work in #229.
In particular, I love the idea of handling the `tokio::spawn` and `tokio::task::spawn_blocking` on our side, because it handles the 99% case beautifully. Folks that want even finer control can always implement `Handler` themselves.
Changes here:
- Remove `handler_fn` (which took `(Request, Responder)` as arguments).
- Rename `sync_handler_fn` as `handler_fn`.
- Add `blocking_handler_fn` and `async_handler_fn` for blocking and async function handlers.
- Remove some useless `'static` bounds.
> rust: Improve service handler wrappers

- python/foxglove-sdk/python/foxglove/_foxglove_py/__init__.pyi
- python/foxglove-sdk/python/foxglove/_foxglove_py/channels.pyi
- python/foxglove-sdk/python/foxglove/channel.py
- python/foxglove-sdk/python/foxglove/tests/test_channel.py
- python/foxglove-sdk/src/generated/channels.rs
- python/foxglove-sdk/src/lib.rs
- rust/foxglove/src/channel.rs
- typescript/schemas/src/internal/generatePyclass.ts
Allow python implementations to explicitly close their channels, in order to stop advertisements to the app.
For both typed channels and BaseChannel, each python class stores the reference to the underlying channel as an option, and sets it to None when closed. Calling `log` after this results in debug logging, but does not raise an error.
I have not added this to any examples; I think this is a niche requirement which is not typically needed.
> python: add close method to channels

- rust/foxglove/src/websocket/tests.rs
This should mitigate a flaky test related to message queue size, by putting more messages on the channel (example: https://github.com/foxglove/foxglove-sdk/actions/runs/13598790792/job/38021236440). Prior to this, it failed about 50% of the time locally for me.
> Mitigate flaky test

- README.md
- Update readme with with new python and rust SDKs (with disclaimer about beta status)
- Remove references to packages not contained in this repo
> readme: Add python and rust packages

- python/foxglove-sdk-examples/live-visualization/main.py
- python/foxglove-sdk/python/foxglove/_foxglove_py/schemas_wkt.pyi
- python/foxglove-sdk/python/foxglove/tests/test_time.py
- python/foxglove-sdk/src/schemas_wkt.rs
- rust/examples/ws-server/src/main.rs
- rust/foxglove/src/schemas_wkt.rs
- rust/foxglove/src/schemas_wkt/chrono.rs
- rust/foxglove/src/schemas_wkt/tests.rs
This change adds the following conversions into Duration and Timestamp for python:
- `Duration.from_secs(secs: float)`
- `Duration.from_timedelta(td: datetime.timedelta)`
- `Timestamp.from_epoch_secs(timestamp: float)`
- `Timestamp.from_datetime(dt: datetime.datetime)`
> python: Add conversions for Duration and Timestamp

- .github/workflows/python.yml
None
None
Fix python docs building to run only after Python release.
> fix doc building to only build for releases

- rust/foxglove/src/websocket/tests.rs
Skips over any msgN messages until finding the disconnect message. This makes the test robust if the consumer and producer happen to interleave in a way that one or more of the messages go through.
Hopefully this is enough now.
> Fix flakey test

- rust/foxglove/src/channel.rs
- rust/foxglove/src/log_context.rs
- rust/foxglove/src/log_sink.rs
- rust/foxglove/src/mcap_writer/mcap_sink.rs
- rust/foxglove/src/testutil/log_sink.rs
- rust/foxglove/src/websocket.rs
I think we can relax `&Arc<Channel>` to just `&Channel` in `LogSink::log`.
> rust: Demote &Arc<Channel> to &Channel

- python/foxglove-sdk/python/foxglove/channel.py
I watched @amacneil today as he did this:
```python
chan = Channel("topic", message_encoding="msgpack", schema={ ... })
```
That doesn't work as expected, because we automatically override the message_encoding to be json when you provide a schema that looks like a dict jsonschema. Which is a silly thing to do, in retrospect. The schema encoding does not imply a message encoding.
> python: Don't override message_schema for json schemas

- python/foxglove-sdk/src/generated/schemas.rs
- rust/foxglove-proto-gen/src/lib.rs
- rust/foxglove/src/schemas/foxglove.rs
- typescript/schemas/src/internal/generatePyclass.test.ts
- typescript/schemas/src/internal/generatePyclass.ts
For bytes fields on protobufs, we should use `Bytes` instead of `Vec<u8>`. This enables zero-copy for buffers that are already `Bytes` of course, but also for types `T: AsRef<[u8]> + Send + 'static` (via [`Bytes::from_owner`](https://docs.rs/bytes/latest/bytes/struct.Bytes.html#method.from_owner)), such as you'd find for an `Arc<Vec<u8>>` or [Mmap](https://docs.rs/memmap/latest/memmap/struct.Mmap.html) or other various memory views.
> rust: Use Bytes instead of Vec<u8> in protobufs

- python/foxglove-sdk-examples/live-visualization/main.py
- python/foxglove-sdk-examples/ws-connection-graph/main.py
- python/foxglove-sdk-examples/ws-param-server/main.py
- python/foxglove-sdk-examples/ws-services/main.py
- python/foxglove-sdk-examples/ws-stream-mcap/main.py
- python/foxglove-sdk/python/docs/api/index.rst
- python/foxglove-sdk/python/foxglove/__init__.py
- python/foxglove-sdk/python/foxglove/_foxglove_py/__init__.pyi
- python/foxglove-sdk/python/foxglove/_foxglove_py/websocket.pyi
- python/foxglove-sdk/python/foxglove/tests/test_server.py
- python/foxglove-sdk/python/foxglove/websocket.py
- python/foxglove-sdk/src/lib.rs
- python/foxglove-sdk/src/websocket.rs
- [python] Move websocket-related classes into a `websocket` module
None
This re-organizes existing python code by introducing a `websocket` module. `start_server` is still in the top-level namespace, along with all other functions. I think we could go either way on this, but this sort of follows the rust organization, which has the server at the top level, with supporting classes in a websocket module.
> python: organize websocket code into submodule

- .github/workflows/c_cpp.yml
- cpp/.clang-tidy
- cpp/CMakeLists.txt
- cpp/Makefile
- cpp/README.md
- cpp/examples/ws-server/src/main.cpp
- cpp/foxglove/include/foxglove/server.hpp
- cpp/foxglove/src/server.cpp
- cpp/foxglove/tests/test_server.cpp
None
None
More C++ linting via https://clang.llvm.org/extra/clang-tidy/
> Run clang-tidy in CI

- .github/workflows/python.yml
- python/foxglove-sdk/CONTRIBUTING.md
- python/foxglove-sdk/poetry.lock
- python/foxglove-sdk/pyproject.toml
- python/foxglove-sdk/python/foxglove/tests/test_channel.py
- python/foxglove-sdk/python/foxglove/tests/test_logging.py
- python/foxglove-sdk/python/foxglove/tests/test_mcap.py
- python/foxglove-sdk/python/foxglove/tests/test_server.py
- python/foxglove-sdk/python/foxglove/tests/test_time.py
None
This adds `pytest` to the SDK dev dependencies, and rewrites the tests from unittest.
Note that you no longer need to cd into the inner python directory to run tests.
Supports FG-10513.
> python: migrate to pytest in sdk

- .github/workflows/ci.yml
- rust/foxglove/src/websocket/connection_graph.rs
None
None
This adds a CI step generate rust docs and fail if any warnings are encountered; also fixes a couple of warnings. The capability here was only a broken link, but this should guard against invalid identifiers as well.
> Check for doc warnings

- rust/foxglove/src/context.rs
- rust/foxglove/src/lib.rs
- rust/foxglove/src/mcap_writer/mcap_sink.rs
- rust/foxglove/src/sink.rs
- rust/foxglove/src/testutil/sink.rs
- rust/foxglove/src/websocket.rs
- rust: Add `SinkId` and new mandatory `Sink::id()` trait method.
We've been using Arc pointers to compare log sinks, which is… fine. But it'd be a bit nicer if we just had a SinkId to use, like we have a ChannelId. That would give us a natural way of indexing sinks, which will be useful for both sink deregistration as well as subscription management.
> rust: Add SinkId for identifying sinks

- rust/foxglove/src/channel.rs
- rust/foxglove/src/context.rs
- rust/foxglove/src/encode.rs
- rust/foxglove/src/log_sink_set.rs
- rust/foxglove/src/mcap_writer.rs
- rust/foxglove/src/sink.rs
- rust/foxglove/src/testutil/sink.rs
- rust/foxglove/src/websocket.rs
- rust/foxglove/src/websocket_server.rs
- Skip message serialization for a `TypedChannel` that has no subscribed sinks.
- rust: Add `Channel::has_sinks` and `TypedChannel::has_sinks`.
- rust: Hide `Sink` trait for now.
This change enhances the old channel->sinks linkage with the new subscription manager.
Structural changes:
- `Context` is now an `RwLock` wrapper around an inner struct.
- Most updates impact multiple resources.
- Difficult to reason about sequencing and raciness.
- The lock should be mostly uncontended.
- `ContextInner`:
- Holds a `Subscriptions` instance, which it uses to update channel sinks.
- Indexes sinks by `SinkId`, instead of by `Arc` pointer.
- Indexes channels by `ChannelId` in addition to topic, to support (un)subscribe-by-id.
- `Channel` no longer implements `Drop`; its lifecycle is managed by the …
> rust: Use subscription manager

- .github/workflows/python.yml
PR CI runs are [failing](https://github.com/foxglove/foxglove-sdk/actions/runs/13958484508/job/39075110751?pr=293) in the `python.yml` workflow:
```
FAILED tests/test_schemas.py::test_schemas - google.protobuf.runtime_version.VersionError: Detected incompatible Protobuf Gencode/Runtime versions when loading foxglove/RawImage.proto: gencode 5.29.4 runtime 5.29.3. Runtime version cannot be older than the linked gencode version. See Protobuf version guarantees at https://protobuf.dev/support/cross-version-runtime-guarantee.
```
From [the linked article](https://protobuf.dev/support/cross-version-runtime-guarantee/):
> New Gencode + Old Runtime = Never Allowed
So let's pin CI to use the same version that we currently have locked for `foxglove-schemas-protobuf`.
> ci: Pin protoc to 5.29.3

- rust/foxglove/src/websocket.rs
- rust/foxglove/src/websocket/tests.rs
- rust/foxglove/src/websocket/unstable_tests.rs
- rust/foxglove/src/websocket_server.rs
- Skip message serialization for a `TypedChannel` that has no subscribed websocket clients.
This change makes use of the new subscription manager, to teach the websocket to manage channel subscriptions dynamically based on client demand. The websocket no longer automatically subscribes to all channels. Instead, it only subscribes to channels that have one or more subscribed clients.
To make that happen, we move the implementation of `Sink` from `Server` to `ConnectedClient`. This is a bit simpler than the alternative, which would involve maintaining an aggregation layer for propagating client subscriptions back to the context. Anyway, it feels a bit more natural to treat the clients as sinks.
> rust: Manage websocket channel subscriptions dynamically

- Cargo.lock
- rust/foxglove/Cargo.toml
- rust/foxglove/src/channel.rs
- rust/foxglove/src/channel_builder.rs
- rust/foxglove/src/context.rs
- rust/foxglove/src/encode.rs
- rust/foxglove/src/mcap_writer/mcap_sink.rs
- rust/foxglove/src/websocket.rs
- rust/foxglove/src/websocket/protocol/server.rs
- rust/foxglove/src/websocket/tests.rs
- rust: Added various getter methods to `Channel` and `TypedChannel`.
This change has three objectives:
- Add `pub(crate) Channel::new` constructor
- Make `Channel` fields private
- Add getter methods to both `Channel` and `TypedChannel`
> rust: Make channel fields private

- rust/foxglove/src/channel.rs
- rust/foxglove/src/log_sink_set.rs
- rust/foxglove/src/tests/logging.rs
- rust/foxglove/src/testutil.rs
- rust/foxglove/src/websocket/tests.rs
Now that we have websocket clients represented as individual sinks, we can remove a couple arbitrary 100ms sleeps from our tests, and instead periodically poll the number of subscribed sinks on a channel.
While we're at it, we might as well get rid of some other arbitrary sleeps as well, by polling on `RecordingServerListener` state, or simply waiting to receive messages on the websocket client.
I ran tests in a loop on my machine for ten minutes and didn't see any failures.
> rust: Remove arbitrary sleeps from tests

- Cargo.lock
- jest.config.json
- rust/examples/ws-services/src/client.rs
- rust/examples/ws-services/src/server.rs
- rust/foxglove/Cargo.toml
- rust/foxglove/src/websocket/protocol/server.rs
- rust/foxglove/src/websocket/protocol/snapshots/foxglove__websocket__protocol__server__tests__advertise_services.snap
When I implemented websocket services, I didn't know about the Service Call panel in the UI, and so I did all my testing with a custom client in rust. Turns out I botched the request/response schema encoding.
This change fixes the schema encoding, using the same logic that we use for encoding channel schemas. The ws-services example is now compatible with the UI.
> rust: Fix websocket service schema encoding

- python/foxglove-sdk/python/foxglove/__init__.py
- python/foxglove-sdk/python/foxglove/channel.py
[python] Re-organize some undocumented imports (private API)
Currently our `foxglove` module imports classes & functions from the generated `_foxglove_py` library, making them available through the public module. This adjusts the import definitions so that we only re-export items that we intend to. For example, `BaseChannel` is not intended to be part of the public API today.
> Hide _foxglove_py imports where possible

- rust/examples/client-publish/src/main.rs
- rust/examples/param-server/src/main.rs
- rust/examples/ws-server-blocking/src/main.rs
- rust/examples/ws-server-fetch-asset/src/main.rs
- rust/examples/ws-server/src/main.rs
- rust/examples/ws-services/src/server.rs
- rust/foxglove/src/channel.rs
- rust/foxglove/src/channel_builder.rs
- rust/foxglove/src/encode.rs
- rust/foxglove/src/sink.rs
- rust/foxglove/src/websocket.rs
- rust/foxglove/src/websocket/fetch_asset.rs
- rust/foxglove/src/websocket/protocol/client.rs
- rust/foxglove/src/websocket/protocol/server.rs
- rust/foxglove/src/websocket/service.rs
- rust/foxglove/src/websocket/service/request.rs
Odds and ends included here:
- For ws examples, use the crate name as the ws server name.
- Add `Display` impl for newtyped IDs.
- Hide `new()` constructors for IDs that users shouldn't create.
- Adjust `Debug` impls for `Schema` and `Request` to elide payloads.
- Derive `Clone` and `Eq` for a few public structures where it makes sense.
- Fix client-publish example by advertising support for JSON encoding
> rust: Miscellaneous tidying

- rust/foxglove/src/channel.rs
- rust/foxglove/src/lib.rs
rust: Expose `ChannelId` struct
TBD
In my custom Sink, I'd like to use a `HashMap<ChannelId, T>`. This PR exposes the `ChannelId` struct publicly to support that use case.
> rust: Expose ChannelId struct

- c/src/lib.rs
- cpp/CMakeLists.txt
- cpp/foxglove/tests/test_mcap.cpp
- cpp/foxglove/tests/test_server.cpp
C++: fixed a potential use-after-free by adding a missing copy.
None
Reported in #320 
It was intended that the Schema data should never be used again after the Channel constructor, but because it was held by a Cow, it was not actually being copied. Introduce an explicit `to_owned()` to fix the issue.
> Fix lifetime issues

- rust/foxglove/src/channel.rs
rust: Expose `ChannelId::new`
None
Allows for conversion from u64 to `ChannelId`.
> rust: Expose ChannelId::new

- c/src/lib.rs
- python/foxglove-sdk/src/generated/channels.rs
- python/foxglove-sdk/src/lib.rs
- rust/examples-unstable/ws-stream-mcap/src/main.rs
- rust/examples/client-publish/src/main.rs
- rust/examples/mcap/src/main.rs
- rust/examples/quickstart/src/main.rs
- rust/examples/ws-server-blocking/src/main.rs
- rust/examples/ws-server/src/main.rs
- rust/foxglove/README.md
- rust/foxglove/src/channel.rs
- rust/foxglove/src/channel/raw_channel.rs
- rust/foxglove/src/channel_builder.rs
- rust/foxglove/src/context.rs
- rust/foxglove/src/context/subscriptions.rs
- rust/foxglove/src/context/subscriptions/tests.rs
- rust/foxglove/src/encode.rs
- rust/foxglove/src/lib.rs
- rust/foxglove/src/mcap_writer/mcap_sink.rs
- rust/foxglove/src/schema.rs
- rust/foxglove/src/schemas.rs
- rust/foxglove/src/sink.rs
- rust/foxglove/src/tests/logging.rs
- rust/foxglove/src/testutil.rs
- rust/foxglove/src/testutil/sink.rs
- rust/foxglove/src/websocket.rs
- rust/foxglove/src/websocket/protocol/client.rs
- rust/foxglove/src/websocket/protocol/server.rs
- rust/foxglove/src/websocket/tests.rs
- typescript/schemas/src/internal/generatePyclass.ts
- rust: Renamed `Channel` to `RawChannel`, and `TypedChannel` to `Channel`.
We realized that we want to encourage rust users to use the typed channel interface, rather than the untyped one. This change adjusts the naming of those structs to be `Channel` and `RawChannel`.
> rust: Rename Channel->RawChannel, TypedChannel->Channel

- rust/foxglove/src/websocket.rs
None
None
Tiny optimization. If no services are being added, there is no need to send a message to clients.
> websocket: don't send msg for empty add_services call

- python/foxglove-sdk/src/lib.rs
- python: Fixed a bug with Channel.close(), which wasn't unregistering the channel
A straightforward change to make `Channel.close()` behave as advertised by unregistering the channel from the context.
> python: Channel.close() should remove channel from context

- rust/foxglove/src/schemas_wkt.rs
Take the suggestion from FG-10911 to improve the wording of the docs for `Duration::new` and `Duration::new_checked`.
> rust: Clarify docs for Duration::new

- Cargo.lock
- rust/foxglove/Cargo.toml
- rust/foxglove/src/channel.rs
- rust/foxglove/src/encode.rs
Improve logging performance by ~20%
This actually simplifies the code. I had to bring in the SmallBytes crate for a BufMut wrapper around SmallVec.
> Optimize buffering in log_to_sinks

- python/foxglove-sdk/src/schemas_wkt.rs
- rust/foxglove/src/schemas_wkt.rs
- rust/foxglove/src/schemas_wkt/tests.rs
I really wanted a Timestamp::now() method during the hack week. The try_from SystemTime works, but it's verbose.
> Add Timestamp::now() convenience method

- rust/examples/mcap/src/main.rs
- rust/examples/quickstart/src/main.rs
- rust/examples/ws-server-blocking/src/main.rs
- rust/examples/ws-server/src/main.rs
- rust/foxglove/src/channel.rs
- rust/foxglove/src/channel/lazy_channel.rs
- rust/foxglove/src/channel_builder.rs
- rust/foxglove/src/lib.rs
- rust: Replace `static_channel!` with `LazyChannel`
This change attempts to address some of the feedback we've received recently:
- `static_channel!` is weird, and merely obscures typing.
- Lazily-initialized channels are a footgun.
This change aims to address both concerns by introducing a new `LazyChannel` struct. This removes the macro weirdness, and updates the naming to make the laziness more overt.
The result is a little more verbose, but I think the clarity justifies the keystrokes:
```rust
// Before
static_channel!(pub(crate), TF, FrameTransform);
// After
pub(crate) static TF: LazyChannel<FrameTransform> = LazyChannel::new("/tf");
```
Fixes: FG-10886
Fixes: FG-10913
> rust: Replace static_channel! with LazyChannel

- python/foxglove-sdk/python/foxglove/channel.py
- python/foxglove-sdk/python/foxglove/tests/test_channel.py
- python/foxglove-sdk/src/generated/channels.rs
- python/foxglove-sdk/src/lib.rs
- rust/foxglove/src/channel.rs
- rust/foxglove/src/channel/raw_channel.rs
- rust/foxglove/src/channel_builder.rs
- rust/foxglove/src/context.rs
- rust/foxglove/src/lib.rs
- rust/foxglove/src/mcap_writer/mcap_sink.rs
- rust/foxglove/src/throttler.rs
- typescript/schemas/src/internal/generatePyclass.ts
- rust: Add `Channel::close`
As part of making `Context` public, I realized that we probably don't want to expose `Context::remove_channel_for_topic()`. We should really be removing channels by ID, to avoid TOCTOU errors. We should expose this functionality publicly as `Channel::close()`, to mirror the python `Channel.close`.
While I was doing that, I realized that [my fix for python's `Channel.close`](https://github.com/foxglove/foxglove-sdk/pull/329) should've also removed a lie in the docstrings ("Destroying all references to the channel will also close it") and completely missed updating the generated typed channels. So this change fakes care of those things too.
The python SDK issues a (debug-level) warning when attempting to log on a channel that was explicitly closed. In this …
> rust: Add Channel::close

- rust/foxglove/src/channel/lazy_channel.rs
- rust/foxglove/src/channel_builder.rs
- rust/foxglove/src/context.rs
- rust/foxglove/src/context/lazy_context.rs
- rust/foxglove/src/lib.rs
- rust/foxglove/src/mcap_writer.rs
- rust/foxglove/src/websocket_server.rs
- rust: Add Context and LazyContext
This change unhides `Context` from the public API. The bulk of the change is:
- Updating documentation to describe contexts.
- Add shortcut methods for building channels & sinks from a context.
- Add a `LazyContext` for use with `LazyChannel`.
Fixes: FG-10885
Fixes: FG-10854
> rust: Make Context public, add LazyContext

- .github/workflows/c_cpp.yml
C/C++: added prebuilt `.a`/`.dylib`s for iOS & iOS Simulator
None
I tried adding the other Apple targets too (watchOS, tvOS, visionOS) but they weren't supported with this current CI workflow setup, probably because they are Tier 3 targets: https://rust-lang.github.io/rustup-components-history/
> Add prebuilt C library for iOS & simulator

- .github/workflows/ci.yml
- rust/foxglove/Cargo.toml
Turns out we need to provide docs.rs with [configuration](https://docs.rs/about/metadata), if we want it to build with --all-features so that non-default features get documented. Not so surprising in retrospect.
Docs.rs generates docs with +nightly, which opens up features like [doc_auto_cfg](https://github.com/rust-lang/rust/issues/43781), which is the handy thing that annotates feature-flagged items as "available on crate feature <foo> only". To indicate that we're running in a docsrs-y environment, we pass `--cfg docsrs`. This idea is lifted from [tokio](https://github.com/tokio-rs/tokio/blob/0ec4d0db4d24af74cea40cf0ceed6b7a0a5ff183/tokio/Cargo.toml#L160-L161).
I also updated the CI script to run rustdoc with nightly and `--cfg docsrs` so that we get coverage.
> rust: Ensure feature-flagged items are documented

- rust/foxglove/src/channel.rs
- rust/foxglove/src/channel/raw_channel.rs
- rust/foxglove/src/mcap_writer.rs
- rust/foxglove/src/metadata.rs
- rust/foxglove/src/websocket_server.rs
This updates the rust documentation in a few places.
Resolves FG-10856: remove 'omitted' comments from required fields
Resolves FG-10907: document buffering behavior of log sinks
> rust: Document buffering behavior

- python/foxglove-sdk/python/foxglove/websocket.py
- rust/foxglove/src/websocket.rs
- rust/foxglove/src/websocket/tests.rs
When a WS client disconnects, a server listener will receive an `on_unsubscribe` event for all subscribed channels.
A Foxglove (WS) client may disconnect without explicitly unsubscribing; a server listener should be made aware of this via the `on_unsubscribe` callback.
> Call `on_unsubscribe` when client disconnects

- python/foxglove-sdk/poetry.lock
- python/foxglove-sdk/pyproject.toml
- python/foxglove-sdk/python/docs/api/index.rst
- python/foxglove-sdk/python/docs/conf.py
- python/foxglove-sdk/python/docs/index.rst
- python/foxglove-sdk/python/docs/version.py
- python/foxglove-sdk/python/foxglove/__init__.py
- python/foxglove-sdk/python/foxglove/_foxglove_py/schemas_wkt.pyi
- python/foxglove-sdk/python/foxglove/_foxglove_py/websocket.pyi
- python/foxglove-sdk/python/foxglove/channel.py
- python/foxglove-sdk/python/foxglove/websocket.py
- python/foxglove-sdk/src/generated/channels.rs
- python/foxglove-sdk/src/schemas_wkt.rs
- python/foxglove-sdk/src/websocket.rs
- scripts/bumpSdkVersion.ts
- typescript/schemas/src/internal/generatePyclass.ts
None
This updates and fixes python documentation, and improves the sphinx configuration for better cross-reference validation.
- Restore the `websocket` submodule documentation, as automodule is not recursive
- Add the "sphinx-autodoc-typehints" extension so types can typically be inferred from type definitions rather than needing to include `:type` docs
- Configure sphinx with "nitpicky", which warns on various issues including broken cross-references. (CI is configured to fail on warnings)
- Add a version to the published documentation; `release` is included in page titles automatically.
> Fix up python docs

- Cargo.lock
- rust/examples/mcap/Cargo.toml
- rust/examples/mcap/src/main.rs
- rust/examples/quickstart/Cargo.toml
- rust/foxglove/src/encode.rs
- rust/foxglove/src/lib.rs
- rust/foxglove/src/mcap_writer.rs
Rust: SDK now re-exports the `bytes` crate (for implementing the `Encode` trait) and MCAP options for writing
> Re-export mcap and bytes dependencies

- package.json
- python/foxglove-sdk-examples/live-visualization/pyproject.toml
- python/foxglove-sdk-examples/quickstart/pyproject.toml
- python/foxglove-sdk-examples/write-mcap-file/pyproject.toml
- python/foxglove-sdk-examples/ws-asset-server/pyproject.toml
- python/foxglove-sdk-examples/ws-connection-graph/pyproject.toml
- python/foxglove-sdk-examples/ws-param-server/pyproject.toml
- python/foxglove-sdk-examples/ws-services/pyproject.toml
- python/foxglove-sdk-examples/ws-stream-mcap/pyproject.toml
- scripts/runPythonSdkExamples.ts
python: update examples to use the published package
We no longer require local build environments to run these python examples.
> python: use published SDK for examples

- rust/foxglove/src/lib.rs
Add documentation for the `chrono` feature in the rust crate.
> rust: Add documentation for chrono feature

- rust/foxglove/src/schemas_wkt.rs
rust: Fix timestamp overflow documentation
This applies the same doc improvement from #328 (Duration) to Timestamp.
Fixes #346
> rust: Fix timestamp overflow documentation

- rust/foxglove/src/lib.rs
I spotted a few minor improvements we could make while looking at the published 0.5.0 docs.
> rust: Minor doc cleanup

- rust/foxglove/src/websocket.rs
- rust/foxglove/src/websocket/channel_view.rs
- rust/foxglove/src/websocket/client.rs
- rust/foxglove/src/websocket/handshake.rs
- rust/foxglove/src/websocket/server_listener.rs
Move a few more trivial types out of `websocket.rs`, and add a few getters.
> rust: Add some websocket server getters

- rust/foxglove/src/websocket.rs
- rust/foxglove/src/websocket/tests.rs
- rust/foxglove/src/websocket_server.rs
This should be the last step in separating the client from the server, so they can move into different modules.
The idea is to encapsulate the poll loop, so that the server doesn't need to care about its inner workings. It just calls an `async fn Poller::run(self)` which consumes self and returns when the client connection is closed.
While we're at it, we might as well move the whole `WebSocketStream` into the poller, too. That way, we can easily ensure that the connection is shutdown in the appropriate sequence - i.e., there are no races between the poller's send loop and [some external attempt to send a close message](https://github.com/foxglove/foxglove-sdk/pull/360/files#diff-a7f22dab80c06b17a93e48fe59f89fad848400d6a7fd59c40a281af78504dac6L896-L897). But to accomplish that, we need …
> rust: Add websocket connection poller

- rust/foxglove/src/context.rs
- rust/foxglove/src/sink.rs
- rust/foxglove/src/testutil/sink.rs
- rust/foxglove/src/websocket/connected_client.rs
- rust/foxglove/src/websocket/tests.rs
- rust/foxglove/src/websocket/testutil.rs
When a websocket is established, we can advertise channels in batches, rather than one at a time.
> Batch websocket channel advertisements

- .github/workflows/python.yml
- python/foxglove-sdk/src/lib.rs
Setting `FOXGLOVE_SDK_LANGUAGE=python` works locally, but not in CI, because `PyO3/maturin-action` runs the build inside a container, and [cherry-picks env vars](https://github.com/foxglove/foxglove-sdk/actions/runs/14318226568/job/40129192596#step:5:79). We could poke our env var through [using the action's `docker-options` input](https://github.com/PyO3/maturin-action?tab=readme-ov-file#inputs), but I think it's a lot more straightforward to just call `set_sdk_language("python")` from the module entrypoint.
This should also cover the case where someone decides they want to build the python SDK bindings from the sdist.
> python: Fix library annotations

- python/foxglove-sdk/python/foxglove/_foxglove_py/__init__.pyi
- python/foxglove-sdk/python/foxglove/channel.py
- python/foxglove-sdk/python/foxglove/tests/test_channel.py
- python/foxglove-sdk/src/lib.rs
This improves the handling of schema definitions which aren't given a name. Previously, we defaulted to a hard-coded string. This produces warnings in the app if you create multiple channels with unnamed schemas. Now, we'll generate based on a hash of the schema contents so that differing schemas will have different names, with reasonable probability. I used base64 encoding and prefixed with "schema-" so that labeling within the app is clear to users.
This also exposes `topic` and `schema_name` on the Channel, and improves the serialized representation of the channel class.
> python: fix default schema names; provide topic and schema getters

- python/foxglove-sdk/python/foxglove/_foxglove_py/__init__.pyi
- python/foxglove-sdk/python/foxglove/_foxglove_py/channels.pyi
- python/foxglove-sdk/python/foxglove/channel.py
- python/foxglove-sdk/python/foxglove/tests/test_channel.py
- python/foxglove-sdk/src/generated/channels.rs
- python/foxglove-sdk/src/lib.rs
- typescript/schemas/src/internal/generatePyclass.ts
This adds `id()` to the Python channel interface. We publish subscription notifications on the server callback interface with these IDs, but they were not meaningful until now.
This also updates the typed channel interface with public getters for schema and topic name to match the raw channel getters added in #368.
> python: fix channel interface to provide ID

- .github/workflows/c_cpp.yml
- .github/workflows/draft-release.yml
- CONTRIBUTING.md
This makes the release artifacts from the C/C++ CI workflow available on a draft release.
A draft release can't have assets with duplicate file names, so I zipped the artifacts prior to uploading, which will preserve the original library filenames once extracted. I put the shared & static libraries in the same zip because it seemed a little easier to find what you're looking for, but of course it increases the download size (particularly for shared); we could produce a zip for each.
These changes produced [this v0.6.0 draft](https://github.com/foxglove/foxglove-sdk/releases/tag/untagged-29e1bf6fd156a0a64220).
> C/C++: Add artifacts to release assets

- c/build.rs
- c/cbindgen.toml
- c/include/foxglove-c/foxglove-c.h
- c/src/lib.rs
- cpp/foxglove/src/channel.cpp
- cpp/foxglove/src/mcap.cpp
- cpp/foxglove/src/server.cpp
- cpp/foxglove/tests/test_server.cpp
None
This replaces usage of `CStr` with a `FoxgloveString` type having an associated length, per https://github.com/foxglove/foxglove-sdk/pull/295#discussion_r2002095320. I also updated the MCAP options which used separate length parameters.
> c++: Remove usage of CStr

- python/foxglove-sdk/python/docs/api/index.rst
- python/foxglove-sdk/python/docs/conf.py
- python/foxglove-sdk/python/foxglove/__init__.py
- python/foxglove-sdk/python/foxglove/_foxglove_py/__init__.pyi
- python/foxglove-sdk/python/foxglove/_foxglove_py/mcap.pyi
- python/foxglove-sdk/python/foxglove/mcap.py
- python/foxglove-sdk/python/foxglove/tests/test_mcap.py
- python/foxglove-sdk/src/lib.rs
- python/foxglove-sdk/src/mcap.rs
python: Add MCAP write options
python: [deprecation] `MCAPWriter` moved to the `foxglove.mcap` module
This exposes MCAP writer options in the python SDK. I omitted some options which are not useful today: file metadata and attachments are not used; `disable_seek` is only useful if you control the rust writer; `library` is used by the SDK. I think we should consider removing these from C++ and Rust as appropriate.
The options here otherwise match the rust writer options; note that this differs from the python mcap library.
This also introduces a `foxglove.mcap` submodule. MCAPWriter is re-exported from `foxglove` to avoid a breaking change, but is documented as deprecated.
> python: Add MCAP write options

- .github/workflows/c_cpp.yml
- .vscode/settings.json
- cpp/CMakeLists.txt
- cpp/Makefile
This updates some C++ config as follows.
Set CXX_STANDARD 17 on all targets. The [CMAKE variables we have set now](https://github.com/foxglove/foxglove-sdk/blob/7767f4855b75ece70f916db983d63c73db5b59fe/cpp/CMakeLists.txt#L9-L10) only apply to new targets when added (hence quickstart being the only one it applied to).
Add a VSCode-specific setting for cppStandard; I couldn't get it to coordinate with CMake.
Ignore "expected.hpp" from our linter. This was CC0 code added for error handling in #350; newer versions of clang-format report errors on it. (The modified find command was harder to read than piping through grep, in my opinion.)
> Update some CMake and lint config

- rust/examples/param-server/src/main.rs
- rust/foxglove/src/websocket/ws_protocol/client/set_parameters.rs
- rust/foxglove/src/websocket/ws_protocol/parameter.rs
- rust/foxglove/src/websocket/ws_protocol/server/parameter_values.rs
- rust/foxglove/src/websocket/ws_protocol/snapshots/foxglove__websocket__ws_protocol__parameter__tests__string.snap
- rust: Fixed Parameter::string() constructor, which was producing a byte array
The `Parameter::string()` constructor was mistakenly returning a byte array, when it should've been returning a string.
This change also updates `Parameter::float64_array()` to accept an `impl IntoIterator<Item = f64>` and updates the rust `param-server` example.
> rust: Parameter::string() should not produce a byte array

- python/foxglove-sdk-examples/ws-param-server/main.py
- python/foxglove-sdk/python/docs/api/index.rst
- python/foxglove-sdk/python/foxglove/_foxglove_py/websocket.pyi
- python/foxglove-sdk/src/websocket.rs
- rust/foxglove/src/websocket.rs
- rust/foxglove/src/websocket/ws_protocol/client/set_parameters.rs
- rust/foxglove/src/websocket/ws_protocol/client/snapshots/foxglove__websocket__ws_protocol__client__set_parameters__tests__encode.snap
- rust/foxglove/src/websocket/ws_protocol/client/snapshots/foxglove__websocket__ws_protocol__client__set_parameters__tests__encode_with_id.snap
- rust/foxglove/src/websocket/ws_protocol/parameter.rs
- rust/foxglove/src/websocket/ws_protocol/server/parameter_values.rs
- rust/foxglove/src/websocket/ws_protocol/server/snapshots/foxglove__websocket__ws_protocol__server__parameter_values__tests__encode.snap
- rust/foxglove/src/websocket/ws_protocol/server/snapshots/foxglove__websocket__ws_protocol__server__parameter_values__tests__encode_with_id.snap
- rust/foxglove/src/websocket/ws_protocol/snapshots/foxglove__websocket__ws_protocol__parameter__tests__string.snap
Breaking changes:
- String websocket parameters are not base64-encoded
I realized while plumbing C++ parameters that we're not representing string parameter values properly. The [example](https://github.com/foxglove/ws-protocol/blob/main/docs/spec.md#example-5) from the ws-protocol spec clearly shows that strings values are only supposed to be encoded when the parameter type is specified as `byte_array`.
This change:
- Replaces `ParameterValue::String(Vec<u8>)` with `ParameterValue::String(String)`.
- Adds `Parameter::decode_byte_array()` helper.
- I didn't extend this to python yet, because we don't have the encode side either. (cf. FG-11299)
- Replaces python `ParameterValue.Bytes(value: bytes)` with `ParameterValue.String(value: str)`.
> String parameters must not be base64-encoded

- Cargo.lock
- python/foxglove-sdk-examples/ws-param-server/main.py
- python/foxglove-sdk/Cargo.toml
- python/foxglove-sdk/python/foxglove/_foxglove_py/websocket.pyi
- python/foxglove-sdk/python/foxglove/tests/test_parameters.py
- python/foxglove-sdk/python/foxglove/websocket.py
- python/foxglove-sdk/src/websocket.rs
- python: Improved websocket parameters
The purpose of this change is to make websocket parameters more ergonomic in python, by implementing conversions to and from native python types.
The basic idea is that we can infer the (type, value) from the type information on a python object, so that the caller doesn't need to specify it explicitly. Likewise, we can convert (type, value) back to a single native python object using a `get_value()` method.
The implementation gets just a tiny bit hairy, because we need to introduce some shim types to accomplish the conversions, but generally, pyo3's trait system works in our favor.
> python: Improved websocket parameters

- Cargo.lock
- python/foxglove-sdk/src/websocket.rs
- rust/examples/ws-server-fetch-asset/Cargo.toml
- rust/examples/ws-server-fetch-asset/src/main.rs
- rust/examples/ws-services/src/server.rs
- rust/foxglove/src/websocket/client.rs
- rust/foxglove/src/websocket/fetch_asset.rs
- rust/foxglove/src/websocket/service.rs
- rust/foxglove/src/websocket/service/handler.rs
- rust/foxglove/src/websocket/service/response.rs
- rust/foxglove/src/websocket/service/tests.rs
- rust/foxglove/src/websocket/tests.rs
- rust/foxglove/src/websocket_server.rs
- rust: Breaking: Changed websocket FetchAsset and Service handler types
I originally proposed we use `bytes::Bytes` for websocket responders, which works fine for callback wrappers that need to return an owned/static value, but it's too restrictive for the underlying responder methods, which would be perfectly happy with any `T: AsRef<[u8]>`.
And so, the core of this change is updating [`service::Responder::respond`](https://github.com/foxglove/foxglove-sdk/pull/395/files#diff-0dc13b18578dee88e4a12ad6685a031c1b807dbe8ced9cb5151cc6253e93c9d4R52-R55) and [`AssetResponder::respond`](https://github.com/foxglove/foxglove-sdk/pull/395/files#diff-48005a706a82df3099ed9cd1dd2586acb02efc3d24d32abfd702dabc4173528dR80-R84) to accept a `T: AsRef<[u8]>`.
Since that change breaks compatibility (albeit …
> rust: Rework websocket responder payload types

- cpp/.clang-tidy
- cpp/Makefile
- cpp/examples/connection-graph/src/main.cpp
- cpp/examples/mcap/src/main.cpp
- cpp/examples/quickstart/src/main.cpp
- cpp/examples/ws-server/src/main.cpp
- cpp/foxglove/include/foxglove/channel.hpp
- cpp/foxglove/include/foxglove/context.hpp
- cpp/foxglove/include/foxglove/mcap.hpp
- cpp/foxglove/include/foxglove/server.hpp
- cpp/foxglove/include/foxglove/server/connection_graph.hpp
- cpp/foxglove/src/channel.cpp
- cpp/foxglove/src/context.cpp
- cpp/foxglove/src/mcap.cpp
- cpp/foxglove/src/server.cpp
- cpp/foxglove/src/server/connection_graph.cpp
- cpp/foxglove/tests/test_mcap.cpp
- cpp/foxglove/tests/test_server.cpp
c++: Breaking: parameters such as mcap writer options are now snake_case
This fixes clang-tidy settings to include our C++ header files as well, and fixes some of the resulting warnings.
This also adds `readability-identifier-naming` casing options to clang-tidy, which accounts for most of the changes here.
The settings generally Google's style guide but use `camelBack` for methods rather than initial caps. That's what we've favored so far; the main change here, then, is to use snake_case for variables, etc. The other change I added was to trailing underscore for private members; since there are some specific restrictions related to leading underscores, it seemed easier to enforce the latter.
The casing changes here do involve some breaking changes, and are up for debate.
I omitted global …
> Add readability-identifier-naming rules

- cpp/foxglove/include/foxglove/error.hpp
- cpp/foxglove/src/server.cpp
If a user-provided callback in C++ raises an exception, that currently causes an inscrutable panic in rust followed by a SIGABRT. Instead, we should catch exceptions, log a message to stderr, and move on.
> C++: Catch callback exceptions

- .github/workflows/c_cpp.yml
- cpp/.gitignore
- cpp/CMakeLists.txt
- cpp/Doxyfile
- cpp/Makefile
- cpp/foxglove/include/foxglove/error.hpp
This adds Doxygen generation to the  C++ CI workflow. We may build documentation around this rather than using the HTML output directly, but it will fail CI if we're missing any public documentation.
Supports FG-11290.
> Generate C++ documentation in CI

- c/include/foxglove-c/foxglove-c.h
- c/src/lib.rs
- cpp/examples/param-server/src/main.cpp
- cpp/foxglove/include/foxglove/server.hpp
- cpp/foxglove/src/server.cpp
- cpp/foxglove/tests/test_server.cpp
- C/C++: Add support for websocket parameters
This change is a follow-up on #383, to finish adding support for websocket parameter subscriptions and publishing.
I tried to remove a little boilerplate for the server setup in our tests. While I was doing that, I noticed that the C++ WebSocketServer is RAII - it shuts down the server when it is dropped. So I got rid of some explicit `server.stop()` calls too.
> C/C++: Add support for websocket parameter subscriptions

- cpp/CMakeLists.txt
Not sure why I didn't do this _before_ working on a giant stack of C++ PRs.
> C++: Use ccache, where available

- .github/workflows/ci.yml
I noticed with #415 breaks the `example-mcap` build, but it isn't caught in CI, because we're building the entire workspace all at once, which means we're building dependencies with the union of all features specified by all target packages.
This change adds a step to CI to build each example individually, to ensure that we don't break them when we introduce new feature flags. We only need to do this for examples, because we already build the other targets individually.
> ci: Build rust examples individually

- rust/foxglove/src/lib.rs
None.
Is a docs PR.
Today there is a code snippet showing the user how to use the foxglove SDK, but to use it they must wrap it in a function that returns `Result<T, E> where E: From<FoxgloveError>`. This means they'd need to write non-trivial extra code to use this code as written. This PR updates the example to use `expect`, which allows a user to get started immediately from `cargo init .; cargo add foxglove`.
<table><tr><th>Before</th><th>After</th></tr><tr><td>
</td><td>
</td></tr></table>
> rust: make toplevel example snippet pastable into any function

- rust/foxglove/src/log_macro.rs
Add a warning to the docs for log! and add a test case covering the behavior.
> Add warning to docs about using log! in functions generic on message

- c/include/foxglove-c/foxglove-c.h
- c/src/lib.rs
- cpp/foxglove/include/foxglove/error.hpp
- rust/foxglove-derive/src/lib.rs
- rust/foxglove-derive/tests/scalar_fields_test.rs
- rust/foxglove-derive/tests/string_fields_test.rs
- rust/foxglove/src/encode.rs
- rust/foxglove/src/lib.rs
- rust/foxglove/src/protobuf.rs
This builds on #324, and is a follow-up to #396.
The primary change is to add a required `encoded_len` method to the ProtobufField trait. This provides the length of encoded data to `Encode::encode`, which will now return an error if the remaining buffer is too short to hold the written data.
This also adds a compiler check for unit-only enums; any variant with fields will now provide a nicer error message.
This also updates the documentation, and notes the protobuf limitation around enum values.
This also fixes the encoding of tags, which were previously written as a single byte. I capped the derived field numbers to 2047, which makes it a little easier to think about encoded_len and avoids thinking about reserved ranges or other limits.
> Add encoding_len to ProtobufField

- typescript/schemas/package.json
TS: fixed missing dependency on `@foxglove/rosmsg-msgs-common`
None
This was moved to devDependencies in https://github.com/foxglove/foxglove-sdk/pull/170, however there are some exported functions whose type definitions depend on it (admittedly they are under `internal`, but we use them for generating docs). The missing dependency caused TS errors downstream.
> TS: move rosmsg-msgs-common back to dependencies, bump to 1.7.1

- c/Cargo.toml
- python/foxglove-sdk/Cargo.toml
- rust/examples/ws_server/Cargo.toml
- rust/examples/ws_server_blocking/Cargo.toml
- rust/foxglove/Cargo.toml
- rust/foxglove/src/lib.rs
None
None
As @defunctzombie points out, the `derive` feature is a core component of the SDK. Let's enable it by default.
> rust: Enable derive feature by default

- cpp/foxglove/include/foxglove/schemas.hpp
- typescript/schemas/src/internal/generateSdkCpp.ts
This removes the non-zero default values for C++ schemas to match Rust and Python.
The reasoning:
There weren't many fields with a non-zero default value, and while w=1.0 makes sense for quarternion, the values make less sense for vectors and colors.
Rust has default of 0 as defined by prost protobuf library, and we can't change that, so if we use non-zero defaults elsewhere it won't be consistent across the sdk.
Having everything default to 0, but a couple exceptions could be surprising to developers.
We didn't document the defaults: https://docs.foxglove.dev/docs/visualization/message-schemas/quaternion
Slack discussion: https://foxglove.slack.com/archives/C07RB3SSJE5/p1747846188213449
> Don't use default values from schemas for C++

- Cargo.lock
- python/foxglove-sdk/python/foxglove/_foxglove_py/websocket.pyi
- python/foxglove-sdk/python/foxglove/tests/test_server.py
- python/foxglove-sdk/src/websocket.rs
- rust/examples/ws_server/src/main.rs
- rust/foxglove/Cargo.toml
- rust/foxglove/src/app_url.rs
- rust/foxglove/src/lib.rs
- rust/foxglove/src/websocket/server.rs
- rust/foxglove/src/websocket_server.rs
- rust, python: Add websocket server method to get app URL
None
This change adds a method to the websocket server handle to return an app URL that you can use to open the websocket as a data source, with an optional layout.
> Add websocket server method to get app URL

- Cargo.lock
- Cargo.toml
- rust/examples/ws_stream_mcap/Cargo.toml
- rust/examples/ws_stream_mcap/src/main.rs
A shotgun approach towards getting dependabot to a stable baseline.
> rust: Upgrade mcap, update other deps

- c/src/tests.rs
None
FoxgloveString.data is a `*const c_char`; this fixes the cast in a test for some architectures.
> Cast to c_char in test

- cpp/foxglove/include/foxglove/arena.hpp
- cpp/foxglove/include/foxglove/mcap.hpp
Fix assertion failure in C++ when serializing empty vectors
arena.hpp:73: T *foxglove::Arena::alloc(size_t) [T = foxglove_scene_entity_deletion]: Assertion `elements > 0' failed.
The problem was that arena alloc expects a non-zero allocation, but arena map was calling it without checking the number of elements for 0 first. This checks and returns a nullptr for empty arrays. This means they're passed to C as a nullptr with length 0, which fits with how we represent empty arrays and strings.
While I was at it, I noticed that forward declaring context and errors in mcap.hpp meant that you had to include both of those headers whenever you import mcap.hpp, I changed this to match how we did channel.hpp and server.hpp, which makes it a little more friendly to use.
> C++ fix assertion crash copying zero-length vectors via the arena

- python/foxglove-sdk/python/foxglove/_foxglove_py/schemas_wkt.pyi
Fix: python: Add missing stub for Timestamp.now()
None
We have a Timestamp.now() implementation, but were missing the stub interface.
> python: Add missing stub for Timestamp.now()

- .gitattributes
This marks additional generated code to be hidden by default in PR diff display. See [docs](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github).
> Update .gitattributes to ignore codegen

- eslint.config.mjs
- python/foxglove-sdk/python/foxglove/channels/__init__.py
- python/foxglove-sdk/src/generated/schemas.rs
- typescript/schemas/src/internal/generatePyclass.test.ts
- typescript/schemas/src/internal/generatePyclass.ts
None
None
This adds support for multi-line python `:param` descriptions on schemas, which will be rendered in generated documentation. It converts code blocks and links from markdown to rst.
This also fixes a couple of param names which used the Rust `r#type` instead of the python name.
> python: support multi-line :param docs

- c/include/foxglove-c/foxglove-c.h
- c/src/lib.rs
- cpp/foxglove/include/foxglove/channel.hpp
- cpp/foxglove/src/channel.cpp
- cpp/foxglove/tests/test_channel.cpp
c++: Add channel.close() method
This adds a close() method to channels in C++.
This is based on #472 because the test makes use of a getter from there.
> c++: Add channel.close() method

- .github/workflows/python.yml
@eloff and I have both been bit by [inscrutable build failures in CI](https://github.com/foxglove/foxglove-sdk/actions/runs/15645870788/job/44083140389), where the jobs to build python linux wheels fail to find glibc. I'm pretty sure that this is related to a bad caching strategy. I suspect that if we drop the `setup-rust-toolchain` step from the job, it'll prevent this problem from happening in the future.
We don't really benefit from that step anyway. The maturin-action takes care of installing the rust toolchain. The comment about rustfmt is stale; we used to do rust codegen as part of the python build, but that's ancient history.
> ci: Don't do setup-rust-toolchain in python-linux builds

- cpp/foxglove/docs/index.rst
- python/foxglove-sdk/README.md
- python/foxglove-sdk/python/docs/index.rst
- rust/foxglove/src/lib.rs
None
This improves the main reference doc page in all languages, to make it easier to get started with the SDK, and introduce the concepts (from the Rust docs) in Python and C++.
> Improve "getting started" reference docs

- Cargo.lock
- rust/examples/prost/.gitignore
- rust/examples/prost/Cargo.toml
- rust/examples/prost/build.rs
- rust/examples/prost/src/apple.proto
- rust/examples/prost/src/main.rs
This example ties together the basic concepts documented by the prost-build, prost, and foxglove crates. It's less flexible than #481, but is a quicker way to get started with custom serialization and protobuf. I think both examples are useful.
> Add a simple prost example

- Container.mk
- cpp/Makefile
- cpp/foxglove/include/foxglove/server/parameter.hpp
This is a PR into the branch for #516, and fixes the doc generation errors there.
We needed to ignore the generation of the `ParameterValueView` specializations in addition to `ParameterView`. The additional `@cond` should solve the bug (see issue noted in comments), and get docs state back to where they were.
I also added some manual documentation of the template parameters, so it's clearer from docs what specializations are available. Given the bug, this is the best way I could find to document them; they're listed as template parameters in addition to `T`, which is a little weird but hopefully less confusing than omitting them.
> Update C++ doc generation for template specialization

- rust/foxglove_data_loader/Cargo.toml
None
This turns off publishing for the foxglove_data_loader crate, since we have not yet published it, to unblock the release process for SDK. FG-12276 tracks the setup needed to publish this new crate.
> Skip publishing data_loader for now

- rust/foxglove/src/websocket/connected_client.rs
- rust/foxglove/src/websocket/tests.rs
Fixed a bug where a channel that fails to be advertised to a websocket client would still be unadvertised. Now unadvertise is only sent if advertise succeeded for a channel.
https://linear.app/foxglove/issue/FG-12137/sdk-websocket-server-should-not-unadvertise-channels-that-it-failed-to
I modified one of our tests to identify this issue and fail, then fixed the bug and verified the test passes now.
> Don't unadvertise a channel if an error prevented it from being advertised

- scripts/bumpSdkVersion.ts
None
One more change to unblock SDK publishing: this skips the version bump on foxglove_data_loader, which is not yet published. FG-12276 will properly set that crate up for publishing.
> Skip version bump on data loader

- python/foxglove-sdk/python/foxglove/__init__.py
- python/foxglove-sdk/python/foxglove/_foxglove_py/__init__.pyi
- python/foxglove-sdk/python/foxglove/tests/test_server.py
- python/foxglove-sdk/src/websocket.rs
Python: add session_id option to start_server
This adds the session_id option to start_server. Typically, the default will work just fine, but we provide this option for other languages, and clear_session() also optionally accepts an explicit ID.
> Python: add session_id option to start_server

- rust/foxglove_data_loader/wit/loader.wit
I'm not sure how this got mixed up, but the app expects the order `info, warn, error`. There was likely a commit I forgot to push when the problems change was added.
> Fix data loader severity enum ordering

- cpp/foxglove/include/foxglove/server/parameter.hpp
Fix a compiler error involving template types.
None
When trying to compile on Ubuntu 24.04 I get the following compiler error
```bash
foxglove-sdk/cpp/foxglove/include/foxglove/server/parameter.hpp:335:50: error: expected unqualified-id before ‘.’ token
335 |       result.emplace(dictKey, dictValue.template .get<T>());
|                                                  ^
foxglove-sdk/cpp/foxglove/include/foxglove/server/parameter.hpp:335:56: error: expected primary-expression before ‘>’ token
335 |       result.emplace(dictKey, dictValue.template .get<T>());
|                                                        ^
foxglove-sdk/cpp/foxglove/include/foxglove/server/parameter.hpp:335:58: error: expected primary-expression before ‘)’ token
335 |       result.emplace(dictKey, …
```
> Fix template type issue

- cpp/foxglove/include/foxglove/channel.hpp
- cpp/foxglove/include/foxglove/server.hpp
- cpp/foxglove/src/channel.cpp
- rust/foxglove/src/channel.rs
- rust/foxglove/src/channel/raw_channel.rs
None
None
This makes the sink-specific logging from #515 'internal': C++ now uses an undocumented `log_` function, and rust methods are undocumented. We'll revert the changes here once we've implemented the same functionality for Python and typed channels, and are ready to release the feature.
> Make sink_id internal

- cpp/examples/foxglove-schemas/src/main.cpp
- cpp/foxglove/include/foxglove/schemas.hpp
- cpp/foxglove/include/foxglove/time.hpp
- cpp/foxglove/tests/test_mcap.cpp
- typescript/schemas/src/internal/generateSdkCpp.ts
C++: (breaking) Move Timestamp and Duration to schemas namespace
This moves `Timestamp` and `Duration` schemas to the `foxglove::schemas` namespace, for consistency with other definitions. This is a breaking change for anyone referencing one of these schemas in the prior namespace.
> C++: Move Timestamp and Duration to schemas namespace

- c/include/foxglove-c/foxglove-c.h
- c/src/parameter.rs
- c/src/parameter/tests.rs
- cpp/foxglove/include/foxglove/server/parameter.hpp
- cpp/foxglove/src/server/parameter.cpp
- cpp/foxglove/tests/test_parameter.cpp
- python/foxglove-sdk/python/docs/api/index.rst
- python/foxglove-sdk/python/foxglove/_foxglove_py/websocket.pyi
- python/foxglove-sdk/python/foxglove/tests/test_parameters.py
- python/foxglove-sdk/python/foxglove/websocket.py
- python/foxglove-sdk/src/websocket.rs
- rust/examples/param_server/src/main.rs
- rust/foxglove/src/websocket/ws_protocol/client/set_parameters.rs
- rust/foxglove/src/websocket/ws_protocol/client/snapshots/foxglove__websocket__ws_protocol__client__set_parameters__tests__encode.snap
- rust/foxglove/src/websocket/ws_protocol/client/snapshots/foxglove__websocket__ws_protocol__client__set_parameters__tests__encode_with_id.snap
- rust/foxglove/src/websocket/ws_protocol/parameter.rs
- rust/foxglove/src/websocket/ws_protocol/snapshots/foxglove__websocket__ws_protocol__parameter__tests__dict.snap
- rust/foxglove/src/websocket/ws_protocol/snapshots/foxglove__websocket__ws_protocol__parameter__tests__integer.snap
- rust/foxglove/src/websocket/ws_protocol/snapshots/foxglove__websocket__ws_protocol__parameter__tests__integer_array.snap
- Introduce an explicit Integer (64-bit signed integer) type for Parameters.
- Rename the Number parameter type to Float64 to make its semantic clearer
- Update Rust/C/C++/Python bindings to allow constructing Integer and IntegerArray parameters, and to rename Number to Float64 for consistency.
Documentation comments updated.
Previously, the Number parameter type was overloaded to represent both integer and floating-point types (this is because when parameters are sent over the wire as JSON, the distinction is lost). SDK users wanting to construct integer parameters needed to cast them to doubles. When these values were round-tripped through the WebSocketServer interface, a fractional part of `.0` was added, which caused some deserialization libraries to treat them as doubles.
While this …
> Introduce explicit integer Parameter type

- c/include/foxglove-c/foxglove-c.h
- c/src/lib.rs
- cpp/foxglove/tests/test_server.cpp
- python/foxglove-sdk/python/foxglove/websocket.py
- rust/foxglove/src/websocket/connected_client.rs
- rust/foxglove/src/websocket/server.rs
- rust/foxglove/src/websocket/server_listener.rs
- rust/foxglove/src/websocket/tests.rs
- rust/foxglove/src/websocket/ws_protocol/parameter.rs
- WebSocket server will no longer send non-existent or deleted parameters in its response body
None
When publishing parameters to clients in response to get_parameter or set_parameter requests, or updates to subscribed parameters, filter out parameters with None values. This brings the SDK implementation in-line with the same observable behavior as [the previous ws-protocol implementation](https://github.com/foxglove/ws-protocol/blob/305d217eec5e38ff8d6b8e8b4f64d9d087193193/cpp/foxglove-websocket/include/foxglove/websocket/websocket_server.hpp#L882-L887).
Part of the motivation here is that, according to [the protocol spec](https://github.com/foxglove/ws-protocol/blob/305d217eec5e38ff8d6b8e8b4f64d9d087193193/cpp/foxglove-websocket/include/foxglove/websocket/websocket_server.hpp#L882-L887): …
> Do not send deleted/non-existent params to clients

- .github/workflows/c_cpp.yml
- c/src/lib.rs
- c/src/parameter.rs
- cpp/CMakeLists.txt
- cpp/Makefile
C++: Fix a precondition assertion from the Rust library which could panic in Debug configurations
This adds an explicit null check for string data in `as_utf8_str`. Without this, Rust's precondition assertion would panic in Debug targets (`-DCMAKE_BUILD_TYPE=Debug`) as described in #526. See [docs](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html#ffi-handling-null-pointers). This also adds similar checks for other public methods using `slice.from_raw_parts`.
This will now also test a Debug build of the C++ SDK in CI.
> C FFI: Add explicit null check for FoxgloveString

- rust/foxglove_data_loader/src/lib.rs
- rust/foxglove_data_loader/wit/loader.wit
None
None
Fleshes out some of the comments on the structs in the WIT that make it to the user but didn't have comments.
Also changes backfill to have an empty default implementation and more comments.
Backfill isn't a strict requirement but does make playback better, so I think having it as an advanced opt-in concept is better.
These docs will be published to docs.rs once the crate is released after #559. So I'll try and get the updates to land before then.
> Flesh out data loader docs, make backfill optional

- .github/workflows/ci.yml
- Cargo.lock
- rust/foxglove_data_loader/Cargo.toml
None
None
Adds a workflow to deploy the `foxglove_data_loader` crate. This avoids extensions needing to use a git dependency. I've set the version to `0.0.1` but we could use a `-beta` version instead.
This will be released separately on the `rust/foxglove_data_loader/v..` tag.
Fixes FG-12509.
> Deploy foxglove data loader crate

- scripts/bumpSdkVersion.ts
None
This updates a stale comment about version generation for foxglove_data_loader. Per #559, we're not releasing this in lockstep with the SDK.
> Update version bump comment

- ros/src/foxglove_bridge/include/foxglove_bridge/ros2_foxglove_bridge.hpp
- ros/src/foxglove_bridge/src/ros2_foxglove_bridge.cpp
None
None
Bugfix PR to have the FoxgloveBridge's WebSocketServer use its own context instead of the SDK's default context. This resolves issues in benchmark tests when instantiating FoxgloveBridge in a tight loop using the global context, where clients could receive messages enqueued by previous iterations of the benchmark.
Fixes: FG-12700
> Use dedicated context in foxglove_bridge

- c/include/foxglove-c/foxglove-c.h
- c/src/generated_types.rs
- c/src/lib.rs
- cpp/foxglove/include/foxglove/channel.hpp
- cpp/foxglove/include/foxglove/schemas.hpp
- cpp/foxglove/src/channel.cpp
- cpp/foxglove/src/schemas.cpp
- cpp/foxglove/tests/test_server.cpp
- python/foxglove-sdk/python/foxglove/_foxglove_py/__init__.pyi
- python/foxglove-sdk/python/foxglove/_foxglove_py/channels.pyi
- python/foxglove-sdk/python/foxglove/channel.py
- python/foxglove-sdk/python/foxglove/tests/test_channel.py
- python/foxglove-sdk/src/generated/channels.rs
- python/foxglove-sdk/src/lib.rs
- ros/src/foxglove_bridge/src/ros2_foxglove_bridge.cpp
- rust/foxglove/src/channel.rs
- rust/foxglove/src/channel/raw_channel.rs
- typescript/schemas/src/internal/generatePyclass.ts
- typescript/schemas/src/internal/generateSdkCpp.ts
- typescript/schemas/src/internal/generateSdkRustCTypes.ts
See #567
This reverts #578 (sink IDs) and re-generates the schemas to produce VoxelGrid logging functions that support it.
> Re-introduce sink_id

- Dockerfile
- c/include/foxglove-c/foxglove-c.h
- c/src/generated_types.rs
- cpp/foxglove/include/foxglove/schemas.hpp
- cpp/foxglove/src/schemas.cpp
- python/foxglove-sdk/python/foxglove/_foxglove_py/channels.pyi
- python/foxglove-sdk/src/generated/channels.rs
None
This re-runs `generate` to update schemas. I hadn't merged latest main into #556 before merging, and it missed a recent addition to the channel interface from v0.11.
> Re-generate LocationFixes

- .github/workflows/publish-ros-bridge.yml
- ros/src/foxglove_bridge/Dockerfile
- ros/src/foxglove_bridge/README.md
- ros/src/foxglove_bridge/package.xml
- [Foxglove Bridge] The public beta of Foxglove Bridge is now packaged as a Docker image in our public image registry
README.md for bridge updated with image pull instructions
Create GHA workflow for pushing a Docker image containing the Foxglove Bridge to our public image registry. This is in response to customer feedback that providing these images helps them more easily deploy Foxglove Bridge.
Images are built against all currently supported versions of ROS. The GHA workflow is currently configured to build the bridge:
- On a push to `main`, where the version identifier will be the git SHA of the commit on `main`
- On an SDK release tag (i.e. `sdk/vxxx`), where the version identifier will be the SDK version number
The version number of Foxglove Bridge is incremented to equal that of …
> Package foxglove_bridge in docker image

- .github/workflows/cpp_data_loader.yml
None
None
The draft release process is broken right now, because job inputs aren't available in the `env` block of a job, apparently.
<table><tr><th>Before</th><th>After</th></tr><tr><td>
</td><td>
</td></tr></table>
> cpp_data_loader.yml: define SDK_VERSION in step

- Dockerfile.ros
- ros/Makefile
None
None
Fix issue in ROS Docker builds under Linux where the passed USER_UID (typically 1000) conflicts with an existing user in the ROS base image. Previously, this seems to have worked but after re-pulling the base system layers, it seems a user now exists with UID 1000. This adds logic to check if a user with that UID already exists and, if so, to use it.
> Fix UID conflict in Dockerfile.ros

- ros/src/foxglove_bridge/src/ros2_foxglove_bridge.cpp
- ros/src/foxglove_bridge/src/ros2_foxglove_bridge_node.cpp
Fix foxglove bridge node occasionally logging errors when shutting down
None
Fixes https://github.com/foxglove/ros-foxglove-bridge/issues/370
When the foxglove bridge node is shutting down, it occasionally logs the following error(s):
```
[WS] Exception caught when closing connection: Couldn't initialize rcl timer handle: the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at ./src/rcl/guard_condition.c:67
```
This PR should fix that by omitting to create the time when the node is shutting down.
> fix errors on bridge shutdown

- playground/src/RunnerWorker.ts
None
None
I realized that clicking "Run" multiple times in a row would throw an error, which was for multiple reasons:
- `mkdir` was failing because the directory already existed
- ...which happened because `rmtree` was not working, because of a "Resource busy" error, which I fixed by adding a `chdir` to leave the target directory before removing it.
> playground: fix directory removal/creation logic

- .github/workflows/python.yml
None.
None.
That's because the cloudflare deploy step requires secrets, which are not passed to a job running on a PR from an external fork.  By skipping it, we lose a bit of convenience, but given that the number of PRs from external forks is minimal, this should be OK.
You can see what happens with an external fork by looking at the CI in https://github.com/foxglove/foxglove-sdk/pull/670 (ignore the CI/rust failure, that's a different problem handled by #671).
> Skip cloudflare deploy step if the PR is from an external fork.

- cpp/foxglove/include/foxglove/channel.hpp
- cpp/foxglove/include/foxglove/schemas.hpp
- typescript/schemas/src/internal/generateSdkCpp.ts
None
C++ docs: specify that the timestamp in channel.log() is nanos since epoch.
> C++: improve docs for log timestamps

- python/foxglove-sdk/python/foxglove/_foxglove_py/__init__.pyi
- python/foxglove-sdk/src/lib.rs
Python: expose Context.default in types & docs
None
This exposes the `Context.default()` method in Python; a user may want to reference it explicitly.
> Python: expose Context.default in types & docs

- python/foxglove-sdk/python/foxglove/tests/test_context.py
- python/foxglove-sdk/src/lib.rs
- Python: Context.default() always returns the same object.
None
There can be only one highlander.
> python: Make Context.default() always return the same object

- README.md
None
None
Alternative to #684 to fix the broken badge. We need to specify the name of the repository, not the package itself. These used to be the same but now the repository is named `foxglove-sdk`.
> Update ROS badges for rolling

- .github/workflows/python.yml
- python/foxglove-sdk-examples/so100-visualization/pyproject.toml
- rust/foxglove/src/websocket_server.rs
None
None
Two separate issues fixed:
1) test-sdk-examples tries to install av v16 which doesn't have wheels for all platforms (no Linux x86 or x64!)
2) windows x86 builds try to use 64bit python when they should use the 32bit version
> Fix python build issues on windows and with sdk examples
