README.md, json-schema/ros/foxglove_msgs/ImageMarkerArray.json, package.json, proto/ros/foxglove_msgs/ImageMarkerArray.proto, scripts/generate.ts, yarn.lock
Added schemas for `foxglove_msgs/ImageMarkerArray`.
Closes https://github.com/foxglove/ros-message-schemas/issues/4
=> Add foxglove_msgs

.github/workflows/ci.yml
=> Run CI on tags and main branch

.github/workflows/ci.yml
=> Fix registry-url

.github/workflows/ci.yml, .yarnrc, ros_foxglove_msgs/CHANGELOG.rst, ros_foxglove_msgs/package.xml
None
Change TS release tags to `releases/typescript/v*` and bump ROS package version to 1.2.0
=> Bump ROS version and change TS tag scheme

LICENSE.md, README.md
=> include license text in repo

schemas/jsonschema/Grid.json, schemas/jsonschema/PackedElementField.json, schemas/jsonschema/PointCloud.json, schemas/proto/foxglove/PackedElementField.proto, schemas/typescript/PackedElementField.ts, src/schemas.ts
Updated description for PackedElementField
=> Update description for PackedElementField

src/schemas.ts
=> Don't export foxglove_CameraCalibration

.github/workflows/ci.yml, ros_foxglove_msgs/CMakeLists.txt, ros_foxglove_msgs/package.xml, ros_foxglove_msgs/test/test_msgs.py
Add a test to attempt to demonstrate that generated ROS msgs are importable from Python.
=> Add test to ROS package build

ros_foxglove_msgs/CMakeLists.txt
Fail ROS build if msg files are not found during the build.
=> Add fatal_error if msg files are not found during CMake build

.gitignore
None
We don't check in this directory
=> Add dist to .gitignore

README.md
None
Show released version for each ROS distro
=> Add ROS version badges to readme

internal/schemas.ts, ros_foxglove_msgs/ros1/CameraCalibration.msg, ros_foxglove_msgs/ros2/CameraCalibration.msg, schemas/README.md, schemas/jsonschema/CameraCalibration.json, schemas/jsonschema/index.ts, schemas/proto/foxglove/CameraCalibration.proto, schemas/ros1/CameraCalibration.msg, schemas/ros2/CameraCalibration.msg, schemas/typescript/CameraCalibration.ts
See https://docs.ros.org/en/noetic/api/sensor_msgs/html/msg/CameraInfo.html
=> CameraCalibration: add note that R is for stereo cameras only

.github/workflows/ci.yml, .vscode/settings.json, python/.flake8, python/.gitignore, python/Makefile, python/Pipfile, python/Pipfile.lock, python/foxglove-schemas-protobuf/README.md, python/foxglove-schemas-protobuf/pyproject.toml, python/foxglove-schemas-protobuf/setup.cfg, python/foxglove-schemas-protobuf/tests/test_schemas.py
Published a new package to PyPI called `foxglove-schemas-protobuf`. Import classes as follows:
```py
from foxglove_schemas_protobuf.RawImage_pb2 import RawImage
```
=> Publish Python generated protobuf code to PyPI

python/foxglove-schemas-protobuf/setup.cfg
Follow-up from #74 to ensure that .pyi files are included in the package
=> Include pyi stubs in foxglove-schemas-protobuf

internal/schemas.ts, package.json, python/foxglove-schemas-protobuf/setup.cfg, ros_foxglove_msgs/CHANGELOG.rst, ros_foxglove_msgs/package.xml, ros_foxglove_msgs/ros1/CubePrimitive.msg, ros_foxglove_msgs/ros2/CubePrimitive.msg, schemas/README.md, schemas/flatbuffer/CubePrimitive.fbs, schemas/jsonschema/CubePrimitive.json, schemas/jsonschema/SceneEntity.json, schemas/jsonschema/SceneUpdate.json, schemas/jsonschema/index.ts, schemas/proto/foxglove/CubePrimitive.proto, schemas/ros1/CubePrimitive.msg, schemas/ros2/CubePrimitive.msg, schemas/typescript/CubePrimitive.ts
Relates to https://github.com/foxglove/website/issues/860
=> Fix typo in CubePrimitive

internal/schemas.ts, ros_foxglove_msgs/ros1/Grid.msg, ros_foxglove_msgs/ros1/PointCloud.msg, ros_foxglove_msgs/ros2/Grid.msg, ros_foxglove_msgs/ros2/PointCloud.msg, schemas/README.md, schemas/flatbuffer/Grid.fbs, schemas/flatbuffer/PointCloud.fbs, schemas/jsonschema/Grid.json, schemas/jsonschema/PointCloud.json, schemas/jsonschema/index.ts, schemas/proto/foxglove/Grid.proto, schemas/proto/foxglove/PointCloud.proto, schemas/ros1/Grid.msg, schemas/ros1/PointCloud.msg, schemas/ros2/Grid.msg, schemas/ros2/PointCloud.msg, schemas/typescript/Grid.ts, schemas/typescript/PointCloud.ts
- Elaborate on required fields for PointCloud and Grid messages 
[FG-1406](https://linear.app/foxglove/issue/FG-1406/document-field-names-for-foxglovegrid-and-foxglovepointcloud)
=> Elaborate on required fields for PointCloud and Grid messages

package.json
=> NPM package v0.7.4

.github/workflows/ci.yml, python/Pipfile, python/Pipfile.lock, python/foxglove-schemas-flatbuffer/README.md, python/foxglove-schemas-protobuf/README.md
- Publish flatbuffer package to PyPI (`pip install foxglove-schemas-flatbuffer`)
=> Publish foxglove-schemas-flatbuffer to PyPI

package.json
- `@foxglove/schemas` 1.0.0 release
=> Bump @foxglove/schemas to 1.0.0

.github/workflows/ci.yml, internal/generateRos.ts, package.json, scripts/updateGeneratedFiles.ts, yarn.lock
- None
Upgrades all dependencies to latest versions
=> Upgrade dependencies

README.md
None (readme only)
Fixes FG-2010
=> add python release instructions to readme

python/foxglove-schemas-flatbuffer/setup.cfg, python/foxglove-schemas-protobuf/setup.cfg, ros_foxglove_msgs/CHANGELOG.rst, ros_foxglove_msgs/package.xml
Been a while since we bumped the ROS package version 😅
=> Bump versions for Python and ROS packages

python/foxglove-schemas-protobuf/setup.cfg
None
Bump foxglove-schemas-protobuf version
=> Bump foxglove-schemas-protobuf version

internal/__snapshots__/exportTypeScriptSchemas.test.ts.snap, internal/schemas.ts, package.json, ros_foxglove_msgs/ros1/RawImage.msg, ros_foxglove_msgs/ros2/RawImage.msg, schemas/README.md, schemas/flatbuffer/RawImage.fbs, schemas/jsonschema/RawImage.json, schemas/jsonschema/index.ts, schemas/proto/foxglove/RawImage.proto, schemas/ros1/RawImage.msg, schemas/ros2/RawImage.msg, schemas/typescript/RawImage.ts
Rename `uyuv` to `uyvy` and add `yuv422_yuy2`.
See https://github.com/foxglove/studio/pull/6445
=> Update RawImage encodings

package.json
Update `foxglove.CompressedVideo` field descriptions
=> Bump minor version to 1.6.1

internal/__snapshots__/exportTypeScriptSchemas.test.ts.snap, internal/schemas.ts, ros_foxglove_msgs/ros1/CompressedImage.msg, ros_foxglove_msgs/ros2/CompressedImage.msg, schemas/README.md, schemas/flatbuffer/CompressedImage.fbs, schemas/jsonschema/CompressedImage.json, schemas/jsonschema/index.ts, schemas/omgidl/foxglove/CompressedImage.idl, schemas/proto/foxglove/CompressedImage.proto, schemas/ros1/CompressedImage.msg, schemas/ros2/CompressedImage.msg, schemas/typescript/CompressedImage.ts
Studio technically support more than only those 3 strings. So we should update the comment to reflect that
=> Update compressedimage format comment

internal/__snapshots__/exportTypeScriptSchemas.test.ts.snap, internal/schemas.ts, package.json, ros_foxglove_msgs/ros1/CompressedVideo.msg, ros_foxglove_msgs/ros2/CompressedVideo.msg, schemas/README.md, schemas/flatbuffer/CompressedVideo.fbs, schemas/jsonschema/CompressedVideo.json, schemas/jsonschema/index.ts, schemas/omgidl/foxglove/CompressedVideo.idl, schemas/proto/foxglove/CompressedVideo.proto, schemas/ros1/CompressedVideo.msg, schemas/ros2/CompressedVideo.msg, schemas/typescript/CompressedVideo.ts
- update CompressedVideo docs to mention annexb
=> Version update for annex b docs

python/foxglove-schemas-protobuf/setup.cfg
Makes newly added messages available in the foxglove-schemas-protobuf package
=> Bump foxglove-schemas-protobuf to 0.2.0

package.json
Bump patch version to 1.6.3.
Includes: 
Image annotation coordinate frame comment: https://github.com/foxglove/schemas/pull/150
=> Update npm package to 1.6.3

package.json
- add expected endianness of RawImage encodings where relevant
<table><tr><th>Before</th><th>After</th></tr><tr><td>
</td><td>
</td></tr></table>
=> Update 1.6.3 -> 1.6.4

.github/workflows/ci.yml
None
None
Add GitHub Actions to publish crate
=> Publish rust crate on tag

rust/foxglove/README.md, rust/foxglove/src/lib.rs
I had a few minor suggestions, but missed the merge boat on the last PR.
=> rust: Minor readme adjustments

rust/foxglove/.vscode/settings.json
This was accidentally committed with #174.
=> Remove errant .vscode/settings.json

rust/foxglove/src/runtime.rs
=> rust: Don't create a runtime during shutdown_runtime

.github/workflows/c_cpp.yml
None
None
Hoping this will fix some sporadic errors in the C++ linux cross build job (see also https://github.com/actions/runner/issues/3720)
=> ci: apt-get update to fix C/C++ workflow

c/include/foxglove-c/foxglove-c.h, c/src/lib.rs
None
None
I meant to include this in #287, but forgot to actually push the last commit before merging...
=> C/C++: address review comments from client publishing

rust/foxglove/src/websocket/protocol/server.rs
=> rust: Actually fix websocket service schema encoding

python/foxglove-sdk-examples/live-visualization/main.py
None
This cleans up the live viz example and fixes a bug with the example subscriber handling. Subscription callbacks are called for each topic, so keep track of what topics clients are subscribed to.
=> python: fix up the live viz example

.github/workflows/python.yml, cpp/CMakeLists.txt
I think this might do it. Leaning heavily on Claude for this fix. I barely understand it, but it works on my machine (tm)
=> Fix build errors with cmake

rust/foxglove/src/websocket.rs, rust/foxglove/src/websocket/cow_vec.rs
This fixes a bug in the websocket server, where the server may accept new connections after `Server::stop()`, and fail to shut them down properly.
The idea is to use `Server::clients` as the point of synchronization. While stopping the server, we take the contents of that `CowVec` and freeze it, so that new clients cannot be added. The concurrent accept loop, if it is still running, may accept a connection, and the server will handshake it, but then immediately shut it down after failing to add it to `self.clients`.
This change also cancels the accept loop a little earlier, to reduce the likelihood of a new connection being accepted once `Server::stop()` is called. I also removed the compare_exchange on `self.started` - once a server instance is stopped, it's stopped forever.
=> rust: Reject websocket clients after Server::stop

typescript/schemas/package.json
=> Bump ts version: v1.7.0

ros/foxglove_msgs/ros1/CompressedImage.msg, ros/foxglove_msgs/ros2/CompressedImage.msg, rust/foxglove/src/schemas/foxglove.rs, schemas/README.md, schemas/flatbuffer/CompressedImage.fbs, schemas/jsonschema/CompressedImage.json, schemas/jsonschema/index.ts, schemas/omgidl/foxglove/CompressedImage.idl, schemas/proto/foxglove/CompressedImage.proto, schemas/ros1/CompressedImage.msg, schemas/ros2/CompressedImage.msg, typescript/schemas/src/internal/__snapshots__/exportTypeScriptSchemas.test.ts.snap, typescript/schemas/src/internal/schemas.ts, typescript/schemas/src/types/CompressedImage.ts
Document support for AVIF image format.
=> Document AVIF image support

python/foxglove-sdk-examples/logging-context/main.py, python/foxglove-sdk-examples/logging-context/pyproject.toml, python/foxglove-sdk-examples/quickstart/main.py, python/foxglove-sdk/python/foxglove/benchmarks/test_mcap_serialization.py, python/foxglove-sdk/python/foxglove/tests/test_channel.py, python/foxglove-sdk/python/foxglove/tests/test_mcap.py, python/foxglove-sdk/python/foxglove/tests/test_server.py
None
None
Minor updates to python examples:
- import `Channel` from the foxglove module (also in some tests)
- Update the context example to use the last published version
=> Update python example

python/foxglove-sdk/src/schemas_wkt.rs, python/foxglove-sdk/src/websocket.rs, rust/examples/channelless/src/main.rs, rust/examples/client-publish/src/main.rs, rust/foxglove/src/lib.rs, rust/foxglove/src/library_version.rs, rust/foxglove/src/log_macro.rs, rust/foxglove/src/schemas_wkt.rs, rust/foxglove/src/websocket/connected_client/poller.rs, rust/foxglove/src/websocket/semaphore.rs, rust/foxglove/src/websocket/server.rs, rust/foxglove/src/websocket/server_listener.rs, rust/foxglove/src/websocket/service.rs, rust/foxglove/src/websocket/tests.rs, rust/foxglove/src/websocket/testutil.rs
I wrote some typos, I saw some typos, I fixed some typos.
Also [typos](https://github.com/crate-ci/typos) is handy.
=> Fix some typos

rust/foxglove/src/websocket/server.rs, rust/foxglove/src/websocket/tests.rs
The websocket server should advertise the SDK library lang/version.
=> websocket: Advertise SDK library version

README.md
=> Fix typo in README alt text

Container.mk, Dockerfile, cpp/CMakeLists.txt, cpp/Makefile
Let's support C++ too, why not.
=> build: Containerize C++ builds too

.gitignore, Container.mk, Dockerfile, Makefile, cpp/CMakeLists.txt, cpp/Makefile
None
None
Move task execution to a makefile, and declare the (non-language-toolchain) ecosystem inside of a docker container.
=> build: containerize everything

CONTRIBUTING.md
None
None
This is the new way to generate schemas that achieves toolchain consistency.
=> Update CONTRIBUTING.md with new generate command

Container.mk, cpp/examples/quickstart/src/main.cpp
None
None
This updates the C++ quickstart to match other languages, using the SceneEntity schema, and matches what's now used in the docs site.
=> Update C++ quickstart

typescript/schemas/package.json
None
None
Release new schemas package for documentation updates.
=> @foxglove/schemas 1.7.2

.github/workflows/c_cpp.yml, Container.mk, cpp/Makefile, cpp/foxglove/include/foxglove/server/parameter.hpp
C++: fixed building with GCC
None
Fixes FG-12176
Fixes #514 
It is 2025, and GCC does not support a C++17 feature 🙃 
It seems like maybe we switched to clang for all platforms in #383 because of this issue?
=> Fix GCC build

rust/foxglove/src/websocket/connected_client.rs, rust/foxglove/src/websocket/tests.rs
Address this comment: https://github.com/foxglove/foxglove-sdk/pull/520#pullrequestreview-2984405393
=> Only track channels that were actually advertised in ConnectedClient::channels

rust/foxglove/src/log_macro.rs
None
This is a quick update to the [documentation of `log!`](https://docs.rs/foxglove/latest/foxglove/macro.log.html) to improve formatting.
=> Improve docs for `log!`

Cargo.lock, rust/foxglove_data_loader/Cargo.toml, rust/foxglove_data_loader/README.md, rust/foxglove_data_loader/src/lib.rs, rust/foxglove_data_loader/src/tests.rs, rust/foxglove_data_loader/wit/loader.wit
None
None
Add in more docs to make the `docs.rs` experience a bit nicer. Also bumps to version `0.1.0` to match the C++ versioning.
=> Flesh out rustdoc, set version to 0.1.0

typescript/schemas/package.json
- Add Timestamp and Duration to JSON schemas (#391)
- Document RawImage encodings (#273)
=> Bump @foxglove/schemas to 1.7.3

.github/workflows/dependabot.yml
None
Automatically approve dependabot PRs, to save everyone a few clicks.
=> Automatically approve dependabot PRs

cpp/examples/ws-server/src/main.cpp, cpp/foxglove/include/foxglove/server.hpp
None
We added initial WSS support for ros-foxglove bridge in #560. General support is still to come (FG-12852). Until that's generally available, let's remove the example and update the docs accordingly.
=> Remove wss example for now

.github/workflows/cpp_data_loader.yml
=> cpp_data_loader.yaml: change underscore to hyphen

python/foxglove-sdk-examples/so100-visualization/pyproject.toml, scripts/runPythonSdkExamples.ts
When ready, this PR will change how we install LeRobot in CI, hopefully without any lfs issues.
=> Change how lerobot is installed
